In [72]:
from dotenv import load_dotenv
import os
import requests
import pandas as pd

In [73]:
# nous allons vérifier que nous accédons sans soucis à nos identifiants .env
load_dotenv()

CLIENT_ID = os.getenv("FRANCE_TRAVAIL_CLIENT_ID")
CLIENT_SECRET = os.getenv("FRANCE_TRAVAIL_CLIENT_SECRET")

print("Client ID chargé :", CLIENT_ID is not None)
print("Client Secret chargé :", CLIENT_SECRET is not None)

Client ID chargé : True
Client Secret chargé : True

In [74]:
# Construction de la requête OAuth afin de vérifier que notre authentification fonctionne

TOKEN_URL = "https://entreprise.francetravail.fr/connexion/oauth2/access_token?realm=/partenaire"

data = {
    "grant_type" :	"client_credentials" ,
    "client_id"	: CLIENT_ID,
    "client_secret"	: CLIENT_SECRET,
    "scope"	: "api_stats-offres-demandes-emploiv1 offresetdemandesemploi"

}

headers = {
    "Content-Type" : "application/x-www-form-urlencoded"
}

response_token = requests.post(TOKEN_URL, data = data , headers = headers)

if response_token.status_code == 200:
    token_data = response_token.json()
    TOKEN = token_data["access_token"]

    print("Token récupéré :", TOKEN is not None)
    print("Scope obtenu :", token_data.get("scope"))
    print("Expiration :", token_data.get("expires_in"), "secondes")
    
else:
    print("Erreur :", response_token.status_code)
    print(response_token.text)

Token récupéré : True
Scope obtenu : api_stats-offres-demandes-emploiv1 offresetdemandesemploi
Expiration : 1499 secondes

In [75]:
# Vérifions que TOKEN contient maintenant le jeton d'accès

token_data = response_token.json()

TOKEN = token_data["access_token"]

print("Token obtenu :", TOKEN is not None)
print("Type :", token_data["token_type"])
print("Expiration :", token_data["expires_in"], "secondes")

print("Scope du token :", token_data["scope"])
print("Type du token :", token_data["token_type"])

Token obtenu : True
Type : Bearer
Expiration : 1499 secondes
Scope du token : api_stats-offres-demandes-emploiv1 offresetdemandesemploi
Type du token : Bearer

Nous allons commencer par récupérer les données des Endpoints de : 
- Catalogue Indicateur, 
- Offres et 
- Demandeurs.
Ainsi, Avant de collecter des statistiques, nous allons savoir quels indicateurs existent, comment ils sont définis et quels paramètres sont nécessaires pour les récupérer. 
Cela nous évitera de multiplier les appels API sans objectif précis.

In [76]:
# Nous allons appeler l'endpoint Catalogue indicateur de l'API Marché du travail 

response = requests.get(
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/referentiel/details-indicateurs",
    headers={
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/json"
    },
    params={
        "codeFamille": "DEMANDEURS",
        "codeIndicateur": "DE_1"
    }
)

print("Status :", response.status_code)
print("URL appelée :", response.url)
print("Réponse :", response.text)

Status : 200
URL appelée : https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/referentiel/details-indicateurs?codeFamille=DEMANDEURS&codeIndicateur=DE_1

In [77]:

# Pour afficher le résultat de manière à ce qu'il soit lisible

import json

print(json.dumps(response.json(), indent=4, ensure_ascii=False))

{
    "listeIndicateurs": [
        {
            "datMaj": "2026-09-23T11:04:21.000+02:00",
            "codeIndicateur": "ACC_1",
            "libelleIndicateur": "Nombre et % des retours à l'emploi AB par durée d'emploi x caractéristiques, Taux de retour (= % par rapport aux AB) par caractéristiques (age, genre)",
            "descriptif": "Définition détaillée : informations sur les sources de données utilisées, les méthodes de calcul, les limitations sur certains axes, les aspects réglementaires éventuels .",
            "codeFamille": "ACCESEMPLOI",
            "disponibiliteIndicateur": 1,
            "listeTypesValeurs": [
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurPrincipale": "O",
                    "codeTypeValeur": "NB_ET_PCT",
                    "numOrdre": 1,
                    "libValeur": "Nombre et % de répartition de ce nombre par caractéristiques.",
                    "libelleValeurSpecifique": "Nombre et % des retours à l'emploi AB par durée d'emploi et caractéristiques"
                },
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurPrincipale": "N",
                    "codeTypeValeur": "TAUX",
                    "numOrdre": 2,
                    "libValeur": "% spécifique (taus de retour, taux de satisfaction .). Il est éventuellement décliné en caractéristiques.",
                    "libelleValeurSpecifique": "Taux de retour (= % par rapport aux AB du mois précédent) par caractéristiques (age, genre)"
                }
            ],
            "listeTypesTerritoiresIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "NAT",
                    "libelleTypeTerritoire": "Niveau National"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "REG",
                    "libelleTypeTerritoire": "Région"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "DEP",
                    "libelleTypeTerritoire": "Département"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "BASBMO",
                    "libelleTypeTerritoire": "Bassin (BMO)"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "EPCI",
                    "libelleTypeTerritoire": "Etablissement public de coopération intercommunale"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "COM",
                    "libelleTypeTerritoire": "Commune"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "CLPE",
                    "libelleTypeTerritoire": "Comité local pour l'emploi"
                }
            ],
            "listeTypesActivitesIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeActivite": "CUMUL",
                    "libelleTypeActivite": "Cumul (toutes activités)"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeActivite": "ROME",
                    "libelleTypeActivite": "Métier (ROME)"
                }
            ],
            "listeTypesPeriodesIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:30.000+02:00",
                    "codeTypePeriode": "TRIMESTRE",
                    "libelleTypePeriode": "Trimestre",
                    "profondeurMax": "12"
                }
            ],
            "listeTypesNomenclaturesIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:12.000+02:00",
                    "codeTypeNomenclature": "DUREEEMP",
                    "libelleTypeNomenclature": "Durée d'emploi (> 1  mois, emploi durable (> 6 mois), Toutes durées)",
                    "listeValeursNomenclaturesIndicateur": [
                        {
                            "datMaj": "2026-09-23T11:04:31.000+02:00",
                            "valeurNomenclature": "SUP1M",
                            "libelleNomenclature": "Emploi > 1 mois"
                        }
                    ]
                }
            ],
            "listeCroisementsIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "BASBMO",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "BASBMO",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "CLPE",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "CLPE",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "COM",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "COM",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "DEP",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "DEP",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "EPCI",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "EPCI",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "NAT",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "NAT",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:22.000+02:00",
                    "codeTypeTerritoire": "REG",
                    "codeTypeActivite": "CUMUL",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                },
                {
                    "datMaj": "2026-09-23T11:04:23.000+02:00",
                    "codeTypeTerritoire": "REG",
                    "codeTypeActivite": "ROME",
                    "codeTypePeriode": "TRIMESTRE",
                    "codeTypeNomenclature": "DUREEEMP",
                    "codeNomenclature": "SUP1M"
                }
            ],
            "listeCaracteristiqueIndicateur": [
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRE",
                    "codeCaracteristique": "H",
                    "libelleCaracteristique": "Hommes"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRE",
                    "codeCaracteristique": "F",
                    "libelleCaracteristique": "Femmes"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "AGE",
                    "codeCaracteristique": "AGE1",
                    "libelleCaracteristique": "15-24 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "AGE",
                    "codeCaracteristique": "AGE2",
                    "libelleCaracteristique": "25-49 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "AGE",
                    "codeCaracteristique": "AGE3",
                    "libelleCaracteristique": "50 ans et +"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "H-AGE1",
                    "libelleCaracteristique": "Hommes - 15-24 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "H-AGE2",
                    "libelleCaracteristique": "Hommes - 25-49 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "H-AGE3",
                    "libelleCaracteristique": "Hommes - 50 ans et +"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "F-AGE1",
                    "libelleCaracteristique": "Femmes - 15-24 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "F-AGE2",
                    "libelleCaracteristique": "Femmes - 25-49 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "GENRExAGE",
                    "codeCaracteristique": "F-AGE3",
                    "libelleCaracteristique": "Femmes - 50 ans et +"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "TYPERET",
                    "codeCaracteristique": "TYPERET1",
                    "libelleCaracteristique": "AFPR/POEI"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "TYPERET",
                    "codeCaracteristique": "TYPERET2",
                    "libelleCaracteristique": "Bascule en catégorie C"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "TYPERET",
                    "codeCaracteristique": "TYPERET3",
                    "libelleCaracteristique": "DPAE durable"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "TYPERET",
                    "codeCaracteristique": "TYPERET4",
                    "libelleCaracteristique": "DPAE de 1 à 6 mois"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "TYPERET",
                    "codeCaracteristique": "TYPERET5",
                    "libelleCaracteristique": "Reprises d'emploi déclarées+passages en E"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "ONQ",
                    "libelleCaracteristique": "Ouvriers non qualifiés"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "OQ",
                    "libelleCaracteristique": "Ouvriers qualifiés"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "ENQ",
                    "libelleCaracteristique": "Employés non qualifiés"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "EQ",
                    "libelleCaracteristique": "Employés qualifiés"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "TECH",
                    "libelleCaracteristique": "Agents de maîtrise / Techniciens"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVQUAL",
                    "codeCaracteristique": "CADRE",
                    "libelleCaracteristique": "Cadres"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVEXP",
                    "codeCaracteristique": "EXP1",
                    "libelleCaracteristique": "Non renseigné"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVEXP",
                    "codeCaracteristique": "EXP2",
                    "libelleCaracteristique": "Moins d'un an"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVEXP",
                    "codeCaracteristique": "EXP3",
                    "libelleCaracteristique": "1 à 2 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVEXP",
                    "codeCaracteristique": "EXP4",
                    "libelleCaracteristique": "2 à 4 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "NIVEXP",
                    "codeCaracteristique": "EXP5",
                    "libelleCaracteristique": "4 ans et +"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "JEUNE",
                    "libelleCaracteristique": "Jeune (-26 ans)"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "SENIOR",
                    "libelleCaracteristique": "Senior (+55 ans)"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "NONQAL",
                    "libelleCaracteristique": "Non Qualifié"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "BAC2EP",
                    "libelleCaracteristique": "Bac+2 et plus"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "EXP2ANS",
                    "libelleCaracteristique": "Expérience > 2 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "LONGUEDUREE",
                    "libelleCaracteristique": "Longue durée"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "RSA",
                    "libelleCaracteristique": "Bénéficiaire du RSA"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "HANDI",
                    "libelleCaracteristique": "Travailleurs en situation d'handicap"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "CPDE",
                    "codeCaracteristique": "QPV",
                    "libelleCaracteristique": "Quartiers Prioritaires de la Ville"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",
                    "codeTypeCaracteristique": "AGE",
                    "codeCaracteristique": "AGE4",
                    "libelleCaracteristique": "25-34 ans"
                },
                {
                    "datMaj": "2026-09-22T00:00:00.000+02:00",

In [78]:
# Nous allons compter et expliquer les indicateurs que nous avons
## Convertissons la reponse json en objet python

catalogue = response.json()

## Vérifions la structure de la response

print("Clés disponibles: ", catalogue.keys())

## Comptons les indicateurs retournés

indicateurs = catalogue.get("listeIndicateurs", [])

print("Nombres indicateurs: ", len(indicateurs))

## Affichons les premiers indicateurs

for indicateur in indicateurs[:10] :
    print(
        indicateur.get("codeIndicateur"),
        indicateur.get("codeFamille"),
        indicateur.get("libelleIndicateur")
    )

Clés disponibles:  dict_keys(['listeIndicateurs'])
Nombres indicateurs:  19
ACC_1 ACCESEMPLOI Nombre et % des retours à l'emploi AB par durée d'emploi x caractéristiques, Taux de retour (= % par rapport aux AB) par caractéristiques (age, genre)
ACC_2 ACCESEMPLOI Nombre et % des accès à l'emploi sorties formation par délai d'accès emploi x durée d'emploi x caractéristiques,Taux d'accès des formés  par caractéristiques
ACC_8 ACCESEMPLOI Nombre et % des retours à l'emploi AB des profils spécifiques x Catégorie Candidat , Taux de retour (= % par rapport aux AB)
CHOM_1 CHOMAGE Taux de chômage
DE_1 DEMANDEURS Nombre et % de DE par catégories x caractéristiques, % par activités (Rome, Compétence)
DE_3 DEMANDEURS Nombre et % de DE sorties formation par caractéristiques, % par activités (Rome, Formation, Compétence)
DE_5 DEMANDEURS Nombre de demandeurs d'emploi enregistrés en entrée (flux) + cumul des 12 derniers mois
DE_8 DEMANDEURS DE avec un profil spécifique par catégories (ABC / Toutes catégories)
DE_9 DEMANDEURS Nombre et % de DE ayant retrouvé un emploi selon le metier recherché (FAP87,FAP21)
DYN_1 DYNEMPLOI DYNEMPLOI

In [79]:
# Nous allons afficher la liste des 19 indicateurs de l'API marché du travail

for indicateur in catalogue["listeIndicateurs"]:
    print("-"*80),
    print( "Code: ", indicateur.get("codeIndicateur")),
    print("Famille", indicateur.get("codeFamille")),
    print("Libéllé", indicateur.get("libelleIndicateur"))

--------------------------------------------------------------------------------
Code:  ACC_1
Famille ACCESEMPLOI
Libéllé Nombre et % des retours à l'emploi AB par durée d'emploi x caractéristiques, Taux de retour (= % par rapport aux AB) par caractéristiques (age, genre)
--------------------------------------------------------------------------------
Code:  ACC_2
Famille ACCESEMPLOI
Libéllé Nombre et % des accès à l'emploi sorties formation par délai d'accès emploi x durée d'emploi x caractéristiques,Taux d'accès des formés  par caractéristiques
--------------------------------------------------------------------------------
Code:  ACC_8
Famille ACCESEMPLOI
Libéllé Nombre et % des retours à l'emploi AB des profils spécifiques x Catégorie Candidat , Taux de retour (= % par rapport aux AB)
--------------------------------------------------------------------------------
Code:  CHOM_1
Famille CHOMAGE
Libéllé Taux de chômage
--------------------------------------------------------------------------------
Code:  DE_1
Famille DEMANDEURS
Libéllé Nombre et % de DE par catégories x caractéristiques, % par activités (Rome, Compétence)
--------------------------------------------------------------------------------
Code:  DE_3
Famille DEMANDEURS
Libéllé Nombre et % de DE sorties formation par caractéristiques, % par activités (Rome, Formation, Compétence)
--------------------------------------------------------------------------------
Code:  DE_5
Famille DEMANDEURS
Libéllé Nombre de demandeurs d'emploi enregistrés en entrée (flux) + cumul des 12 derniers mois
--------------------------------------------------------------------------------
Code:  DE_8
Famille DEMANDEURS
Libéllé DE avec un profil spécifique par catégories (ABC / Toutes catégories)
--------------------------------------------------------------------------------
Code:  DE_9
Famille DEMANDEURS
Libéllé Nombre et % de DE ayant retrouvé un emploi selon le metier recherché (FAP87,FAP21)
--------------------------------------------------------------------------------
Code:  DYN_1
Famille DYNEMPLOI
Libéllé DYNEMPLOI
--------------------------------------------------------------------------------
Code:  EMB_1
Famille EMBAUCHES
Libéllé Nombre et % d'embauches par Catégorie Candidat x durée d'emploi x caractéristiques, % par activités (Rome, Secteur)
--------------------------------------------------------------------------------
Code:  EMB_8
Famille EMBAUCHES
Libéllé Nombre et % d'embauches par profil spécifique de demandeur x Catégorie Candidat
--------------------------------------------------------------------------------
Code:  ETAB_1
Famille ETABLISSEMENTS
Libéllé Nombre et % d'établissements par caractéristiques, % par activités (Secteur)
--------------------------------------------------------------------------------
Code:  OFF_1
Famille OFFRES
Libéllé Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)
--------------------------------------------------------------------------------
Code:  PERSP_2
Famille PERSPECTIVES
Libéllé PERSPECTIVES Employeur
--------------------------------------------------------------------------------
Code:  POP_1
Famille POPULATION
Libéllé Nombre et % population totale par caractéristiques
--------------------------------------------------------------------------------
Code:  POP_2
Famille POPULATION
Libéllé Nombre et % population active par caractéristiques, % population active / population totale par caractéristiques
--------------------------------------------------------------------------------
Code:  SAL_1
Famille SALARIES
Libéllé Nombre et % de salariés par caractéristiques,% par activités (Rome, Famille, Secteur)
--------------------------------------------------------------------------------
Code:  SAL_3
Famille SALARIES
Libéllé Salaires en poste par typlologie salaires (moyen / débutant / expérimenté) x caractéristiques

Cette première version nous permet de recenser les données que nous choisirons pour répondre aux objectifs de notre observatoire de l'emploi. Les indicateurs que nous pourrons sélectionner pour un début sont ceux des offres, des demandeurs d'emploi et des embauches:

- `code:` CHOM_1 `codeFamille :` CHOMAGE et pour `libelleIndicateur: ` Taux de chômage `Utilité pour le projet: ` compléter l'analyse du marché du travail.

- `code:` DE_1 `codeFamille :` DEMANDEURS et pour `libelleIndicateur: ` Nombre et % de DE par catégories x caractéristiques, % par activités (Rome, Compétence);`Utilité pour le projet: ` ce qui nous permettra de répartir les demandeurs d'emploi par catégories et par caractériques.

- `code:` DE_5 `codeFamille :` DEMANDEURS et pour `libelleIndicateur: ` Nombre de demandeurs d'emploi enregistrés en entrée (flux) + cumul des 12 derniers mois;`Utilité pour le projet: ` ce qui nous permettra d'analyser le nombre des demandeurs d'emploi et cumul sur les 12 derniers mois.

-  `code:` DE_9 `codeFamille :` DEMANDEURS et pour `libelleIndicateur: ` Nombre et % de DE ayant retrouvé un emploi selon le metier recherché (FAP87,FAP21);`Utilité pour le projet: ` ce qui nous permettra de connaitre le nombre des demandeurs d'emploi ayant retrouvé un emploi selon le métier recherché.

- `code:` DYN_1 `codeFamille :` DYNEMPLOI et pour `libelleIndicateur: ` DYNEMPLOI Nous n'avons pas encore sa signification exacte, nous l'examinerons si plus amples informations.

- `code:` EMB_1 `codeFamille :` EMBAUCHES et pour `libelleIndicateur: `Nombre et % d'embauches par Catégorie Candidat x durée d'emploi x caractéristiques, % par activités (Rome, Secteur). `Utilité pour le projet: ` Etudier les embauches selon les caractéristiques et les activités.

- `code:` OFF_1 `codeFamille :` OFFRES et pour `libelleIndicateur: ` Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence). `Utilité pour le projet: ` nous allons étudier les offres par térritoire, métier et période.

In [80]:
# Nous allons chercher les informations associées à l'indicateur OFF_1 en affichant sa structure complète

for indicateur in catalogue["listeIndicateurs"]:
    if indicateur.get("codeIndicateur") == "OFF_1" : 
        print(json.dumps(indicateur, indent = 4, ensure_ascii=False))
        break

{
    "datMaj": "2026-09-23T11:04:21.000+02:00",
    "codeIndicateur": "OFF_1",
    "libelleIndicateur": "Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)",
    "descriptif": "Définition détaillée : informations sur les sources de données utilisées, les méthodes de calcul, les limitations sur certains axes, les aspects réglementaires éventuels .",
    "codeFamille": "OFFRES",
    "disponibiliteIndicateur": 1,
    "listeTypesValeurs": [
        {
            "datMaj": "2026-09-23T11:04:31.000+02:00",
            "valeurPrincipale": "O",
            "codeTypeValeur": "NB_ET_PCT",
            "numOrdre": 1,
            "libValeur": "Nombre et % de répartition de ce nombre par caractéristiques.",
            "libelleValeurSpecifique": "Nombre et % d'offres par origine (Pole-emploi / Toutes offres) et caractéristiques"
        },
        {
            "datMaj": "2026-09-23T11:04:31.000+02:00",
            "valeurPrincipale": "N",
            "codeTypeValeur": "PCT_ACT",
            "numOrdre": 2,
            "libValeur": "% par activité : c'est le poids d'une valeur sur une activité donnée par rapport au total des valeurs (cumul toutes actvités). Il est éventuellement décliné en caractéristiques.",
            "libelleValeurSpecifique": "% par activités (Rome, Secteur, Savoir-être, Compétence)"
        }
    ],
    "listeTypesTerritoiresIndicateur": [
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "NAT",
            "libelleTypeTerritoire": "Niveau National"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "REG",
            "libelleTypeTerritoire": "Région"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "DEP",
            "libelleTypeTerritoire": "Département"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "COM",
            "libelleTypeTerritoire": "Commune"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "libelleTypeTerritoire": "Bassin (BMO)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "EPCI",
            "libelleTypeTerritoire": "Etablissement public de coopération intercommunale"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "libelleTypeTerritoire": "Comité local pour l'emploi"
        }
    ],
    "listeTypesActivitesIndicateur": [
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "CUMUL",
            "libelleTypeActivite": "Cumul (toutes activités)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "ETRE",
            "libelleTypeActivite": "Savoir-être"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "MACRO_COMP",
            "libelleTypeActivite": "Macro compétence"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "NAF21",
            "libelleTypeActivite": "Secteur d'activité (NAF21)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "NAF5",
            "libelleTypeActivite": "Secteur d'activité (NAF5)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "NAF88",
            "libelleTypeActivite": "Secteur d'activité (NAF88)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "OBJECTIF",
            "libelleTypeActivite": "Objectif"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "ROME",
            "libelleTypeActivite": "Métier (ROME)"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeActivite": "FILIERE",
            "libelleTypeActivite": "Filière d'activité"
        }
    ],
    "listeTypesPeriodesIndicateur": [
        {
            "datMaj": "2026-09-23T11:04:30.000+02:00",
            "codeTypePeriode": "TRIMESTRE",
            "libelleTypePeriode": "Trimestre",
            "profondeurMax": "12"
        }
    ],
    "listeTypesNomenclaturesIndicateur": [
        {
            "datMaj": "2026-09-23T11:04:12.000+02:00",
            "codeTypeNomenclature": "ORIGINEOFF",
            "libelleTypeNomenclature": "Origine des offres d'emploi (PE, Partenaire .)",
            "listeValeursNomenclaturesIndicateur": [
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurNomenclature": "PE",
                    "libelleNomenclature": "Offres France Travail"
                },
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurNomenclature": "PE-CUMUL12MOIS",
                    "libelleNomenclature": "Cumul 12 derniers mois offres France Travail"
                },
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurNomenclature": "TOFF",
                    "libelleNomenclature": "Toutes offres"
                },
                {
                    "datMaj": "2026-09-23T11:04:31.000+02:00",
                    "valeurNomenclature": "TOFF-CUMUL12MOIS",
                    "libelleNomenclature": "Cumul 12 derniers mois toutes offres"
                }
            ]
        }
    ],
    "listeCroisementsIndicateur": [
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "MACRO_COMP",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "MACRO_COMP",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "MACRO_COMP",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "MACRO_COMP",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF21",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF21",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF21",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF21",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF5",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF5",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF5",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF5",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF88",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF88",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF88",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "NAF88",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "OBJECTIF",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "OBJECTIF",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "OBJECTIF",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "OBJECTIF",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ROME",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ROME",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ROME",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "BASBMO",
            "codeTypeActivite": "ROME",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "CUMUL",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:23.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "ETRE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "PE-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",
            "codeTypeTerritoire": "CLPE",
            "codeTypeActivite": "FILIERE",
            "codeTypePeriode": "TRIMESTRE",
            "codeTypeNomenclature": "ORIGINEOFF",
            "codeNomenclature": "TOFF-CUMUL12MOIS"
        },
        {
            "datMaj": "2026-09-23T11:04:22.000+02:00",

Nous remarquons que OFF_1 contient énormément de paramètres et de combinaisons.

In [81]:
# Nous allons identifier les informations utiles: périodes, territoires, activités disponibles pour OFF_1

## retrouvons la définition complète de OFF_1
off_1 = next(
    item for item in catalogue["listeIndicateurs"]
    if item.get("codeIndicateur") == "OFF_1"
)
# print(off_1)

## Affichons les paramètres utiles pour préparer notre extraction
print("PERIODES")
print(json.dumps(off_1.get("listeTypesPeriodesIndicateur", []), indent =2, ensure_ascii=False))

print("TERRITOIRES")
print(json.dumps(off_1.get("listeTypesTerritoiresIndicateur", []), indent =2, ensure_ascii=False))

print("ACTIVITES")
print(json.dumps(off_1.get("listeTypesActivitesIndicateur", []), indent =2, ensure_ascii=False))

print("NOMMENCLATURES")
print(json.dumps(off_1.get("listeTypesNomenclaturesIndicateur", []), indent =2, ensure_ascii=False))

print("\nNOMBRE DE CROISEMENTS AUTORISÉS")
print(len(off_1.get("listeCroisementsIndicateur", [])))

PERIODES
[
  {
    "datMaj": "2026-09-23T11:04:30.000+02:00",
    "codeTypePeriode": "TRIMESTRE",
    "libelleTypePeriode": "Trimestre",
    "profondeurMax": "12"
  }
]
TERRITOIRES
[
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "NAT",
    "libelleTypeTerritoire": "Niveau National"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "REG",
    "libelleTypeTerritoire": "Région"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "DEP",
    "libelleTypeTerritoire": "Département"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "COM",
    "libelleTypeTerritoire": "Commune"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "BASBMO",
    "libelleTypeTerritoire": "Bassin (BMO)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "EPCI",
    "libelleTypeTerritoire": "Etablissement public de coopération intercommunale"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "CLPE",
    "libelleTypeTerritoire": "Comité local pour l'emploi"
  }
]
ACTIVITES
[
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "CUMUL",
    "libelleTypeActivite": "Cumul (toutes activités)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "ETRE",
    "libelleTypeActivite": "Savoir-être"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "MACRO_COMP",
    "libelleTypeActivite": "Macro compétence"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "NAF21",
    "libelleTypeActivite": "Secteur d'activité (NAF21)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "NAF5",
    "libelleTypeActivite": "Secteur d'activité (NAF5)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "NAF88",
    "libelleTypeActivite": "Secteur d'activité (NAF88)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "OBJECTIF",
    "libelleTypeActivite": "Objectif"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "ROME",
    "libelleTypeActivite": "Métier (ROME)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeActivite": "FILIERE",
    "libelleTypeActivite": "Filière d'activité"
  }
]
NOMMENCLATURES
[
  {
    "datMaj": "2026-09-23T11:04:12.000+02:00",
    "codeTypeNomenclature": "ORIGINEOFF",
    "libelleTypeNomenclature": "Origine des offres d'emploi (PE, Partenaire .)",
    "listeValeursNomenclaturesIndicateur": [
      {
        "datMaj": "2026-09-23T11:04:31.000+02:00",
        "valeurNomenclature": "PE",
        "libelleNomenclature": "Offres France Travail"
      },
      {
        "datMaj": "2026-09-23T11:04:31.000+02:00",
        "valeurNomenclature": "PE-CUMUL12MOIS",
        "libelleNomenclature": "Cumul 12 derniers mois offres France Travail"
      },
      {
        "datMaj": "2026-09-23T11:04:31.000+02:00",
        "valeurNomenclature": "TOFF",
        "libelleNomenclature": "Toutes offres"
      },
      {
        "datMaj": "2026-09-23T11:04:31.000+02:00",
        "valeurNomenclature": "TOFF-CUMUL12MOIS",
        "libelleNomenclature": "Cumul 12 derniers mois toutes offres"
      }
    ]
  }
]

NOMBRE DE CROISEMENTS AUTORISÉS
252

In [82]:
print("TERRITOIRES")
print(json.dumps(off_1.get("listeTypesTerritoiresIndicateur", []), indent =2, ensure_ascii=False))

TERRITOIRES
[
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "NAT",
    "libelleTypeTerritoire": "Niveau National"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "REG",
    "libelleTypeTerritoire": "Région"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "DEP",
    "libelleTypeTerritoire": "Département"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "COM",
    "libelleTypeTerritoire": "Commune"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "BASBMO",
    "libelleTypeTerritoire": "Bassin (BMO)"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "EPCI",
    "libelleTypeTerritoire": "Etablissement public de coopération intercommunale"
  },
  {
    "datMaj": "2026-09-23T11:04:23.000+02:00",
    "codeTypeTerritoire": "CLPE",
    "libelleTypeTerritoire": "Comité local pour l'emploi"
  }
]

Nous apprenons ainsi que OFF_1 permet d'avoir:
- Périodes: Trimestres avec une profondeur maximale de 12.
- Territoires: National, Région, Département, Commune, bassin BMO, EPCI et comité local pour l'emploi.
- Activités: toutes activités, métier ROME, secteurs NAF, savoir-être, macro-compétence, filière ...
- Nomenclature: Origine des offres: France travail, partenaires ou toutes les offres.
- Croisement : 252 combinaisons autorisés. Ce sont des combinaisons possibles entre les caractéristiques. Nous allons sélectionner celles qui répondent à notre objectif métier.

Pour Construire un premier jeu de données exploitable,
nous allons commencer par une analyse des offres d'emploi par métier, par région et par trimestre.
Ce qui nous permettra de répondre à des questions concrètes telles que :
- Quels métiers présentent le plus d'offres d'emploi ?
- Comment le volume d'offre évolue t'il au fil des trimestres ?
- Quelles différences observe t-on entre les régions ?
- Les résultats changent-ils selon que l’on considère les offres France Travail ou toutes les offres ?

Nous avons déjà identifier dans les paramètres:
TRIMESTRE pour la période,
REG pour le térritoire région,
ROME pour le métier,
PE et TOFF pour distinguer l'origine des offres.

In [83]:
# Nous allons afficher les 5 premiers croisements et pas les 252

croisements = off_1.get("listeCroisementsIndicateur", [])

print("Nombre total de Croisements :", len(croisements))

for i, croisement in enumerate(croisements[:5], start = 1) : 
    print(f"\n --- Croisement {i} ---")
    print(json.dumps(croisement, indent = 2, ensure_ascii = False))

Nombre total de Croisements : 252

 --- Croisement 1 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "BASBMO",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

 --- Croisement 2 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "BASBMO",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

 --- Croisement 3 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "BASBMO",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

 --- Croisement 4 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "BASBMO",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

 --- Croisement 5 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "BASBMO",
  "codeTypeActivite": "ETRE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

In [84]:
# Nous observons avec la précédente requête que le codeTypeTerritoire apparait par ordre analphabétique
# Pour vérifier cela, nous allons vérifier la répartition des 252 croisements
# Nous comptons le nombre de croisement par type de territoire

from collections import Counter

repartition = Counter(croisement.get("codeTypeTerritoire")
                        for croisement in croisements
                        )
print("Nombre de croisements par territoire: ")

for territoire, nombre in repartition.items():
    print(f"{territoire} : {nombre}")

Nombre de croisements par territoire:
BASBMO : 36
CLPE : 36
COM : 36
DEP : 36
EPCI : 36
NAT : 36
REG : 36

In [85]:
# Observons dans quel ordre apparait les territoires dans les croisements sans doublons

territoires = [
                croisement.get("codeTypeTerritoire")
                for croisement in croisements
]

territoires_uniques = list(dict.fromkeys(territoires))

print("Ordre des territoires dans la liste :")
print(territoires_uniques)

Ordre des territoires dans la liste :
['BASBMO', 'CLPE', 'COM', 'DEP', 'EPCI', 'NAT', 'REG']

Nous observons de ce fait qu'il y'a 7 territoires et 36 croisements par territoire.

Les sept types de territoires sont :
BASBMO : Bassin BMO
CLPE: Comité local pour l'emploi
COM: Commune
DEP: Département
EPCI: Établissement public de coopération intercommunale
NAT: Niveau national
REG: Région

In [86]:
# Observons les 36 combinaisons d'un territoire - en fonction de RE - région
# Filtrer les croisements de type REG

croisements_reg = [
        croisement
        for croisement in croisements
        if croisement.get("codeTypeTerritoire") == "REG"
]

print("Nombre de croisements régionaux :", len(croisements_reg))

for i, croisement in enumerate(croisements_reg, start=1):
    print(f"\n--- Croisement {i} ---")
    print(json.dumps(croisement, indent=2, ensure_ascii=False))

Nombre de croisements régionaux : 36

--- Croisement 1 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 2 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 3 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 4 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "CUMUL",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 5 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ETRE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 6 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ETRE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 7 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ETRE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 8 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ETRE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 9 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "FILIERE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 10 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "FILIERE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 11 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "FILIERE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 12 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "FILIERE",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 13 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "MACRO_COMP",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 14 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "MACRO_COMP",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 15 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "MACRO_COMP",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 16 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "MACRO_COMP",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 17 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF21",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 18 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF21",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 19 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF21",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 20 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF21",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 21 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF5",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 22 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF5",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 23 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF5",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 24 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF5",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 25 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF88",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 26 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF88",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 27 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF88",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 28 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "NAF88",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 29 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "OBJECTIF",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 30 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "OBJECTIF",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 31 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "OBJECTIF",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

--- Croisement 32 ---
{
  "datMaj": "2026-09-23T11:04:23.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "OBJECTIF",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 33 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ROME",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF-CUMUL12MOIS"
}

--- Croisement 34 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ROME",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "TOFF"
}

--- Croisement 35 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ROME",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE-CUMUL12MOIS"
}

--- Croisement 36 ---
{
  "datMaj": "2026-09-23T11:04:22.000+02:00",
  "codeTypeTerritoire": "REG",
  "codeTypeActivite": "ROME",
  "codeTypePeriode": "TRIMESTRE",
  "codeTypeNomenclature": "ORIGINEOFF",
  "codeNomenclature": "PE"
}

Nous pouvons déduire des 36 croisements que :

Les croisements combinent 9 types d’activité × 4 nomenclatures, toujours avec les mêmes paramètres de période et de territoire. 
Les 9 types d’activité sont CUMUL, ETRE, FILIERE, MACRO_COMP, NAF21, NAF5, NAF88, OBJECTIF et ROME.

Les quatre valeurs de nomenclature sont :

PE : offres France Travail,
PE-CUMUL12MOIS : cumul sur les 12 derniers mois des offres France Travail,
TOFF : toutes les offres,
TOFF-CUMUL12MOIS : cumul sur les 12 derniers mois de toutes les offres.

In [87]:

import requests

url = (
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres"
)

payload = {
    "codeTypeTerritoire": "REG",
    "codeTerritoire": "75",
    "codeTypeActivite": "ROME",
    "codeActivite": "A1203",
    "codeTypePeriode": "TRIMESTRE",
    "codeTypeNomenclature": "ORIGINEOFF",
    "codeNomenclature": "TOFF"
}

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

response = requests.post(
    url,
    json=payload,
    headers=headers
)

print("Statut :", response.status_code)
print("Type de contenu :", response.headers.get("Content-Type"))
print("Réponse :", response.text[:3000])

Statut : 200
Type de contenu : application/json
Réponse : {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)","listeValeursParPeriode":[{"datMaj":"2026-09-23T09:06:21.000+02:00","codeTypeTerritoire":"REG","codeTerritoire":"75","libTerritoire":"NOUVELLE-AQUITAINE","codeTypeActivite":"ROME","codeActivite":"A1203","libActivite":"Agent / Agente d'entretien des espaces verts","codeNomenclature":"PE","libNomenclature":"Offres France Travail","codeTypePeriode":"TRIMESTRE","codePeriode":"2026T2","libPeriode":"2ème trimestre 2026","valeurPrincipaleNombre":290,"valeurSecondairePourcentage":0.0,"listeValeurParCaract":[{"codeTypeCaract":"TYPECTR","codeCaract":"CDI","libCaract":"CDI","nombre":60,"pourcentage":23.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD1","libCaract":"CDD < 1 mois","nombre":0,"pourcentage":1.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD2","libCaract":"CDD de 1 à 6 mois","nombre":80,"pourcentage":31.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD3","libCaract":"CDD > 6 mois","nombre":10,"pourcentage":5.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"AUTR","libCaract":"Autres (intérim, emplois aidés, apprentissage)","nombre":110,"pourcentage":40.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB1","libCaract":"0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB2","libCaract":"10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB3","libCaract":"50 à 250 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB4","libCaract":"250+ salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDI-ETB1","libCaract":"CDI - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD1-ETB1","libCaract":"CDD < 1 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD2-ETB1","libCaract":"CDD de 1 à 6 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD3-ETB1","libCaract":"CDD > 6 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"AUTR-ETB1","libCaract":"Autres (intérim, emplois aidés, apprentissage) - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDI-ETB2","libCaract":"CDI - 10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD1-ETB2","libCaract":"CDD < 1 mois - 10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCa

Nous allons transformer notre résultat JSON en Dataframe.

In [88]:
resultat = response.json()

# Extraire les statistiques par périodes
valeurs = resultat.get("listeValeursParPeriode", [])

df_offres = pd.json_normalize(valeurs)

display(df_offres.head())

,datMaj,codeTypeTerritoire,codeTerritoire,libTerritoire,codeTypeActivite,codeActivite,libActivite,codeNomenclature,libNomenclature,codeTypePeriode,codePeriode,libPeriode,valeurPrincipaleNombre,valeurSecondairePourcentage,listeValeurParCaract
0,2026-09-23T09:06:21.000+02:00,REG,75,NOUVELLE-AQUITAINE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE,Offres France Travail,TRIMESTRE,2026T2,2ème trimestre 2026,290,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
1,2026-09-23T09:06:21.000+02:00,REG,75,NOUVELLE-AQUITAINE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE-CUMUL12MOIS,Cumul 12 derniers mois offres France Travail,TRIMESTRE,2026T2,2ème trimestre 2026,890,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
2,2026-09-23T09:06:23.000+02:00,REG,75,NOUVELLE-AQUITAINE,ROME,A1203,Agent / Agente d'entretien des espaces verts,TOFF,Toutes offres,TRIMESTRE,2026T2,2ème trimestre 2026,390,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
3,2026-09-23T09:06:22.000+02:00,REG,75,NOUVELLE-AQUITAINE,ROME,A1203,Agent / Agente d'entretien des espaces verts,TOFF-CUMUL12MOIS,Cumul 12 derniers mois toutes offres,TRIMESTRE,2026T2,2ème trimestre 2026,1160,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
4,2026-09-23T09:06:21.000+02:00,REG,75,NOUVELLE-AQUITAINE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE,Offres France Travail,TRIMESTRE,2026T1,1er trimestre 2026,260,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."

In [89]:
# informations de notre df_offres

df_offres.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   datMaj                       88 non-null     str
 1   codeTypeTerritoire           88 non-null     str
 2   codeTerritoire               88 non-null     str
 3   libTerritoire                88 non-null     str
 4   codeTypeActivite             88 non-null     str
 5   codeActivite                 88 non-null     str
 6   libActivite                  88 non-null     str
 7   codeNomenclature             88 non-null     str
 8   libNomenclature              88 non-null     str
 9   codeTypePeriode              88 non-null     str
 10  codePeriode                  88 non-null     str
 11  libPeriode                   88 non-null     str
 12  valeurPrincipaleNombre       88 non-null     int64
 13  valeurSecondairePourcentage  88 non-null     float64
 14  listeValeurParCaract         88 non-null     object
dtypes: float64(1), int64(1), object(1), str(12)
memory usage: 10.4+ KB

In [90]:
# Liste des colonnes de df_offres

df_offres.columns

Index(['datMaj', 'codeTypeTerritoire', 'codeTerritoire', 'libTerritoire',
       'codeTypeActivite', 'codeActivite', 'libActivite', 'codeNomenclature',
       'libNomenclature', 'codeTypePeriode', 'codePeriode', 'libPeriode',
       'valeurPrincipaleNombre', 'valeurSecondairePourcentage',
       'listeValeurParCaract'],
      dtype='str')

In [91]:
# Nous allons drop les colonnes qui ne nous sommes pas principales

df_offres = df_offres.drop(columns= ['datMaj', 'listeValeurParCaract'])

In [92]:
# Nos colonnes principales sont:
df_offres.info()

<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   codeTypeTerritoire           88 non-null     str
 1   codeTerritoire               88 non-null     str
 2   libTerritoire                88 non-null     str
 3   codeTypeActivite             88 non-null     str
 4   codeActivite                 88 non-null     str
 5   libActivite                  88 non-null     str
 6   codeNomenclature             88 non-null     str
 7   libNomenclature              88 non-null     str
 8   codeTypePeriode              88 non-null     str
 9   codePeriode                  88 non-null     str
 10  libPeriode                   88 non-null     str
 11  valeurPrincipaleNombre       88 non-null     int64
 12  valeurSecondairePourcentage  88 non-null     float64
dtypes: float64(1), int64(1), str(11)
memory usage: 9.1 KB

df_offres contient :

- 88 lignes : 88 enregistrements statistiques retournés par l'API.

- 13 colonnes : les informations descriptives et les valeurs statistiques principales.

- Aucune valeur manquante dans ces 13 colonnes.

- 2 colonnes numériques : valeurPrincipaleNombre et valeurSecondairePourcentage.

In [93]:
# Nous allons faire une observation des données de ce dataframe

# Nombre de résultats par nomenclature
print(df_offres["codeNomenclature"].value_counts())

# Nombre de résultats par Période

print(df_offres["codePeriode"].value_counts().sort_index())

codeNomenclature
PE                  22
PE-CUMUL12MOIS      22
TOFF                22
TOFF-CUMUL12MOIS    22
Name: count, dtype: int64
codePeriode
2021T1    4
2021T2    4
2021T3    4
2021T4    4
2022T1    4
2022T2    4
2022T3    4
2022T4    4
2023T1    4
2023T2    4
2023T3    4
2023T4    4
2024T1    4
2024T2    4
2024T3    4
2024T4    4
2025T1    4
2025T2    4
2025T3    4
2025T4    4
2026T1    4
2026T2    4
Name: count, dtype: int64

In [94]:
# Vérification des combinaisons de territoires et de métiers

print("Territoires :", df_offres["libTerritoire"].nunique())

print("Territoires :", df_offres["libTerritoire"].unique())

print("Periodes :", df_offres["codeActivite"].nunique())

print("Periodes :", df_offres["codeActivite"].unique())

Territoires : 1
Territoires : <StringArray>
['NOUVELLE-AQUITAINE']
Length: 1, dtype: str
Periodes : 1
Periodes : <StringArray>
['A1203']
Length: 1, dtype: str

L’API renvoie les données du métier A1203, en Nouvelle-Aquitaine, sur 22 trimestres, de 2021T1 à 2026T2, pour quatre nomenclatures :

PE : offres France Travail,
PE-CUMUL12MOIS : cumul sur 12 mois des offres France Travail,
TOFF : toutes les offres,
TOFF-CUMUL12MOIS : cumul sur 12 mois de toutes les offres.

In [95]:
df_offres.columns

Index(['codeTypeTerritoire', 'codeTerritoire', 'libTerritoire',
       'codeTypeActivite', 'codeActivite', 'libActivite', 'codeNomenclature',
       'libNomenclature', 'codeTypePeriode', 'codePeriode', 'libPeriode',
       'valeurPrincipaleNombre', 'valeurSecondairePourcentage'],
      dtype='str')

In [96]:
# Nous allons comparer les 4 nomenclatures sur les derniers trimestres

colonnes = [
            'codePeriode',
            'libPeriode',
            'codeNomenclature',
            'libNomenclature',
            'valeurPrincipaleNombre', 
            'valeurSecondairePourcentage'
        ]

display(df_offres.loc[
            df_offres["codePeriode"].isin(["2026T1" , "2026T2"]),
            colonnes
].sort_values(["codePeriode", "codeNomenclature"])

)

,codePeriode,libPeriode,codeNomenclature,libNomenclature,valeurPrincipaleNombre,valeurSecondairePourcentage
4,2026T1,1er trimestre 2026,PE,Offres France Travail,260,0.0
5,2026T1,1er trimestre 2026,PE-CUMUL12MOIS,Cumul 12 derniers mois offres France Travail,930,0.0
6,2026T1,1er trimestre 2026,TOFF,Toutes offres,360,0.0
7,2026T1,1er trimestre 2026,TOFF-CUMUL12MOIS,Cumul 12 derniers mois toutes offres,1190,0.0
0,2026T2,2ème trimestre 2026,PE,Offres France Travail,290,0.0
1,2026T2,2ème trimestre 2026,PE-CUMUL12MOIS,Cumul 12 derniers mois offres France Travail,890,0.0
2,2026T2,2ème trimestre 2026,TOFF,Toutes offres,390,0.0
3,2026T2,2ème trimestre 2026,TOFF-CUMUL12MOIS,Cumul 12 derniers mois toutes offres,1160,0.0

Pour le métier Agent/Agente d’entretien des espaces verts (ROME A1203) en Nouvelle-Aquitaine, on observe les variations.
Les valeurs du cumul sur 12 mois diminuent alors que les valeurs trimestrielles augmentent.

In [97]:
df_offres.columns

Index(['codeTypeTerritoire', 'codeTerritoire', 'libTerritoire',
       'codeTypeActivite', 'codeActivite', 'libActivite', 'codeNomenclature',
       'libNomenclature', 'codeTypePeriode', 'codePeriode', 'libPeriode',
       'valeurPrincipaleNombre', 'valeurSecondairePourcentage'],
      dtype='str')

In [98]:
# Vérifions maintenant que les quatre nomenclatures sont présentes pour toutes les périodes et qu'il n'y a pas de doublons inattendus.
cols = [
            'codeTerritoire',
            'codeActivite',
            'codePeriode',
            'codeNomenclature',
            'valeurPrincipaleNombre', 
            'valeurSecondairePourcentage'
        ]
print("Nombres de doublons :", df_offres.duplicated(subset=cols).sum())

# Vérifions le nombre de lignes par trimestre

print("Nombres de lignes par trimestre :", df_offres.groupby("codePeriode").size().sort_index())

# Vérifier les valeurs manquantes

print(df_offres.isna().sum())

Nombres de doublons : 0
Nombres de lignes par trimestre : codePeriode
2021T1    4
2021T2    4
2021T3    4
2021T4    4
2022T1    4
2022T2    4
2022T3    4
2022T4    4
2023T1    4
2023T2    4
2023T3    4
2023T4    4
2024T1    4
2024T2    4
2024T3    4
2024T4    4
2025T1    4
2025T2    4
2025T3    4
2025T4    4
2026T1    4
2026T2    4
dtype: int64
codeTypeTerritoire             0
codeTerritoire                 0
libTerritoire                  0
codeTypeActivite               0
codeActivite                   0
libActivite                    0
codeNomenclature               0
libNomenclature                0
codeTypePeriode                0
codePeriode                    0
libPeriode                     0
valeurPrincipaleNombre         0
valeurSecondairePourcentage    0
dtype: int64

Nos observations montrent que :
- absence de doublons
- absence de valeurs manquantes
- Répartition par trimestre : 4 lignes avec une ligne par nomenclature et par trimestre
- Nombre de lignes 88 avec 22 trimestres × 4 nomenclatures.

Pour notre projet, nous allons commencer avec l'indicateur OFF_1 (offres d'emploi), en conservant les quatre nomenclatures et les trimestres disponibles. 
Nous pourrons ensuite élargir la collecte à plusieurs métiers et territoires.

In [99]:

# Nous allons identifier les combinaisons disponibles pour la France métropolitaine les croisements de l'indicateur OFF_1.
# Examinons les types de territoires disponibles
display(off_1["listeTypesTerritoiresIndicateur"])

# Examinons les types d'activités disponibles
display(off_1["listeTypesActivitesIndicateur"])

# Examinons les nomenclatures disponibles
display(off_1["listeTypesNomenclaturesIndicateur"])

[{'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'NAT',
  'libelleTypeTerritoire': 'Niveau National'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'REG',
  'libelleTypeTerritoire': 'Région'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'DEP',
  'libelleTypeTerritoire': 'Département'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'COM',
  'libelleTypeTerritoire': 'Commune'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'libelleTypeTerritoire': 'Bassin (BMO)'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'EPCI',
  'libelleTypeTerritoire': 'Etablissement public de coopération intercommunale'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'CLPE',
  'libelleTypeTerritoire': "Comité local pour l'emploi"}]

[{'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'CUMUL',
  'libelleTypeActivite': 'Cumul (toutes activités)'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'ETRE',
  'libelleTypeActivite': 'Savoir-être'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'MACRO_COMP',
  'libelleTypeActivite': 'Macro compétence'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'NAF21',
  'libelleTypeActivite': "Secteur d'activité (NAF21)"},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'NAF5',
  'libelleTypeActivite': "Secteur d'activité (NAF5)"},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'NAF88',
  'libelleTypeActivite': "Secteur d'activité (NAF88)"},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'OBJECTIF',
  'libelleTypeActivite': 'Objectif'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'ROME',
  'libelleTypeActivite': 'Métier (ROME)'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeActivite': 'FILIERE',
  'libelleTypeActivite': "Filière d'activité"}]

[{'datMaj': '2026-09-23T11:04:12.000+02:00',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'libelleTypeNomenclature': "Origine des offres d'emploi (PE, Partenaire .)",
  'listeValeursNomenclaturesIndicateur': [{'datMaj': '2026-09-23T11:04:31.000+02:00',
    'valeurNomenclature': 'PE',
    'libelleNomenclature': 'Offres France Travail'},
   {'datMaj': '2026-09-23T11:04:31.000+02:00',
    'valeurNomenclature': 'PE-CUMUL12MOIS',
    'libelleNomenclature': 'Cumul 12 derniers mois offres France Travail'},
   {'datMaj': '2026-09-23T11:04:31.000+02:00',
    'valeurNomenclature': 'TOFF',
    'libelleNomenclature': 'Toutes offres'},
   {'datMaj': '2026-09-23T11:04:31.000+02:00',
    'valeurNomenclature': 'TOFF-CUMUL12MOIS',
    'libelleNomenclature': 'Cumul 12 derniers mois toutes offres'}]}]

OFF_1 propose 7 niveaux géographiques mais pour notre première collecte, nous allons nous concentrer sur NAT et REG, afin de commencer par une vue nationale puis de comparer les régions.

In [100]:

# Nous allons afficher les types d'activités autorisés pour OFF_1
for activite in off_1["listeTypesActivitesIndicateur"]:
    print(
        activite.get("codeTypeActivite"),
        "-",
        activite.get("libelleTypeActivite")
    )

CUMUL - Cumul (toutes activités)
ETRE - Savoir-être
MACRO_COMP - Macro compétence
NAF21 - Secteur d'activité (NAF21)
NAF5 - Secteur d'activité (NAF5)
NAF88 - Secteur d'activité (NAF88)
OBJECTIF - Objectif
ROME - Métier (ROME)
FILIERE - Filière d'activité

Nous allons priviligier pour notre collecte les activités de:

- ROME qui nous permettra de classer les métiers selon le nombre d'offres

- NAF21 nous permettra d'identifier les secteurs d'activité qui concentrent le plus d'offres

- CUMUL pourra nous aider à disposer d'une vue globale

In [101]:

croisements = off_1["listeCroisementsIndicateur"]

print("Nombre total de croisements :", len(croisements))
print("\nClés disponibles :")
print(croisements[0].keys())

display(croisements[:5])

Nombre total de croisements : 252

Clés disponibles :
dict_keys(['datMaj', 'codeTypeTerritoire', 'codeTypeActivite', 'codeTypePeriode', 'codeTypeNomenclature', 'codeNomenclature'])

[{'datMaj': '2026-09-23T11:04:22.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'codeTypeActivite': 'CUMUL',
  'codeTypePeriode': 'TRIMESTRE',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'codeNomenclature': 'TOFF-CUMUL12MOIS'},
 {'datMaj': '2026-09-23T11:04:23.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'codeTypeActivite': 'CUMUL',
  'codeTypePeriode': 'TRIMESTRE',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'codeNomenclature': 'PE'},
 {'datMaj': '2026-09-23T11:04:22.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'codeTypeActivite': 'CUMUL',
  'codeTypePeriode': 'TRIMESTRE',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'codeNomenclature': 'TOFF'},
 {'datMaj': '2026-09-23T11:04:22.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'codeTypeActivite': 'CUMUL',
  'codeTypePeriode': 'TRIMESTRE',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'codeNomenclature': 'PE-CUMUL12MOIS'},
 {'datMaj': '2026-09-23T11:04:22.000+02:00',
  'codeTypeTerritoire': 'BASBMO',
  'codeTypeActivite': 'ETRE',
  'codeTypePeriode': 'TRIMESTRE',
  'codeTypeNomenclature': 'ORIGINEOFF',
  'codeNomenclature': 'PE'}]

In [102]:
# Convertir les croisements en DataFrame
df_croisements = pd.DataFrame(croisements)

# Types d'activités retenus pour notre première collecte
activites_cibles = ["ROME", "NAF21", "CUMUL"]

# Nomenclatures utiles pour comparer les offres
nomenclatures_cibles = ["PE", "TOFF"]

# Filtrer les combinaisons utiles
df_plan_collecte = df_croisements[
    df_croisements["codeTypeTerritoire"].isin(["NAT", "REG"])
    & df_croisements["codeTypeActivite"].isin(activites_cibles)
    & df_croisements["codeNomenclature"].isin(nomenclatures_cibles)
].copy()

print("Nombre de croisements retenus :", len(df_plan_collecte))

display(
    df_plan_collecte
    .groupby(
        ["codeTypeTerritoire", "codeTypeActivite", "codeNomenclature"]
    )
    .size()
    .rename("nombre")
    .reset_index()
)

Nombre de croisements retenus : 12

   codeTypeTerritoire codeTypeActivite codeNomenclature  nombre
0                 NAT            CUMUL               PE       1
1                 NAT            CUMUL             TOFF       1
2                 NAT            NAF21               PE       1
3                 NAT            NAF21             TOFF       1
4                 NAT             ROME               PE       1
5                 NAT             ROME             TOFF       1
6                 REG            CUMUL               PE       1
7                 REG            CUMUL             TOFF       1
8                 REG            NAF21               PE       1
9                 REG            NAF21             TOFF       1
10                REG             ROME               PE       1
11                REG             ROME             TOFF       1

In [103]:

display(
    df_plan_collecte[
        df_plan_collecte["codeTypeActivite"].isin(["ROME", "NAF21"])
    ].sort_values(
        ["codeTypeTerritoire", "codeTypeActivite", "codeNomenclature"]
    )
)

,datMaj,codeTypeTerritoire,codeTypeActivite,codeTypePeriode,codeTypeNomenclature,codeNomenclature
197,2026-09-23T11:04:22.000+02:00,NAT,NAF21,TRIMESTRE,ORIGINEOFF,PE
196,2026-09-23T11:04:22.000+02:00,NAT,NAF21,TRIMESTRE,ORIGINEOFF,TOFF
212,2026-09-23T11:04:23.000+02:00,NAT,ROME,TRIMESTRE,ORIGINEOFF,PE
214,2026-09-23T11:04:23.000+02:00,NAT,ROME,TRIMESTRE,ORIGINEOFF,TOFF
232,2026-09-23T11:04:22.000+02:00,REG,NAF21,TRIMESTRE,ORIGINEOFF,PE
235,2026-09-23T11:04:23.000+02:00,REG,NAF21,TRIMESTRE,ORIGINEOFF,TOFF
251,2026-09-23T11:04:22.000+02:00,REG,ROME,TRIMESTRE,ORIGINEOFF,PE
249,2026-09-23T11:04:22.000+02:00,REG,ROME,TRIMESTRE,ORIGINEOFF,TOFF

In [104]:

# Afficher un croisement complet de type ROME au niveau national
croisement_rome_nat = next(
    c for c in croisements
    if c["codeTypeTerritoire"] == "NAT"
    and c["codeTypeActivite"] == "ROME"
    and c["codeNomenclature"] == "PE"
)

display(croisement_rome_nat)

{'datMaj': '2026-09-23T11:04:23.000+02:00',
 'codeTypeTerritoire': 'NAT',
 'codeTypeActivite': 'ROME',
 'codeTypePeriode': 'TRIMESTRE',
 'codeTypeNomenclature': 'ORIGINEOFF',
 'codeNomenclature': 'PE'}

 Pour notre projet, le référentiel des métiers est essentiel : il nous permettra d'obtenir les codes et les libellés nécessaires pour préparer les requêtes statistiques.

In [105]:

# Nous allons appeler l'API ROME 4.0 - Métiers et obtenir un jeton OAuth pour ROME 4.0
TOKEN_URL = (
    "https://entreprise.francetravail.fr/"
    "connexion/oauth2/access_token?realm=/partenaire"
)

data_rome = {
    "grant_type": "client_credentials",
    "client_id": CLIENT_ID,
    "client_secret": CLIENT_SECRET,
    "scope": "api_rome-metiersv1 nomenclatureRome"
}

headers_token = {
    "Content-Type": "application/x-www-form-urlencoded"
}

response_token_rome = requests.post(
    TOKEN_URL,
    data=data_rome,
    headers=headers_token,
    timeout=30
)

print("Statut OAuth ROME :", response_token_rome.status_code)

if response_token_rome.status_code == 200:
    token_data_rome = response_token_rome.json()
    TOKEN_ROME = token_data_rome["access_token"]

    print("Token récupéré :", bool(TOKEN_ROME))
    print("Scope retourné :", token_data_rome.get("scope"))
else:
    print("Réponse :", response_token_rome.text[:1000])

Statut OAuth ROME : 200
Token récupéré : True
Scope retourné : api_rome-metiersv1 nomenclatureRome

In [106]:
# Testons l'endpoint: liste des métiers

url_rome = (
    "https://api.francetravail.io/partenaire/rome-metiers/v1/metiers/metier"
)

headers_rome = {
    "Authorization": f"Bearer {TOKEN_ROME}",
    "Accept": "application/json"
}

response_rome = requests.get(
    url_rome,
    headers=headers_rome,
    timeout=30
)

print("Statut API ROME :", response_rome.status_code)
print("Type de contenu :", response_rome.headers.get("Content-Type"))

if response_rome.status_code == 200:
    donnees_rome = response_rome.json()

    print("Type de réponse :", type(donnees_rome))

    if isinstance(donnees_rome, dict):
        print("Clés disponibles :", donnees_rome.keys())
        display(donnees_rome)
    elif isinstance(donnees_rome, list):
        print("Nombre d'éléments retournés :", len(donnees_rome))
        display(donnees_rome[:5])
else:
    print("Réponse :", response_rome.text[:1500])

Statut API ROME : 200
Type de contenu : application/json
Type de réponse : <class 'list'>
Nombre d'éléments retournés : 1923

[{'code': 'N2215', 'libelle': 'Coordonnateur / Coordonnatrice zone avion'},
 {'code': 'N4207',
  'libelle': 'Régulateur / Régulatrice poste central transport sanitaire de personnes'},
 {'code': 'L1321',
  'libelle': 'Directeur / Directrice de production de spectacles'},
 {'code': 'I1639', 'libelle': "Contrôleur / Contrôleuse de moteurs d'avions"},
 {'code': 'N2217',
  'libelle': "Chef d'équipe contrôleur aérien / Cheffe d'équipe contrôleuse aérienne"}]

Nos deux API marché du travail et ROME 4.0 Métiers répondent correctement.

Elles nous permettront de relier les statistiques aux informations du référentiel métier lorsque les codes le permettent. Cela nous aidera à rendre les résultats plus compréhensibles et à analyser les tendances par métier et par territoire.

In [107]:
# Nous regardons la structure des données ROME
resultat_rome = response_rome.json()
print(resultat_rome)

[{'code': 'N2215', 'libelle': 'Coordonnateur / Coordonnatrice zone avion'}, {'code': 'N4207', 'libelle': 'Régulateur / Régulatrice poste central transport sanitaire de personnes'}, {'code': 'L1321', 'libelle': 'Directeur / Directrice de production de spectacles'}, {'code': 'I1639', 'libelle': "Contrôleur / Contrôleuse de moteurs d'avions"}, {'code': 'N2217', 'libelle': "Chef d'équipe contrôleur aérien / Cheffe d'équipe contrôleuse aérienne"}, {'code': 'K1924', 'libelle': 'Clerc de commissaire de justice'}, {'code': 'K1923', 'libelle': 'Clerc de commissaire-priseur'}, {'code': 'K1231', 'libelle': 'Patient partenaire / Patiente partenaire en santé'}, {'code': 'K1429', 'libelle': "Administrateur / Administratrice de l'Etat"}, {'code': 'K1428', 'libelle': 'Conseiller / Conseillère de cabinet ministériel'}, {'code': 'K2515', 'libelle': 'Agent / Agente cynotechnique en détection des explosifs'}, {'code': 'I1411', 'libelle': 'Agent / Agente de reconditionnement numérique'}, {'code': 'C1124', 'libelle': 'Technicien / Technicienne sécurité sociale'}, {'code': 'K1109', 'libelle': 'Graphothérapeute'}, {'code': 'K1111', 'libelle': 'Psychanalyste'}, {'code': 'J1136', 'libelle': 'Gérontologue'}, {'code': 'J1139', 'libelle': 'Neurochirurgien / Neurochirurgienne'}, {'code': 'K2325', 'libelle': "Technicien / Technicienne d'exploitation méthanisation"}, {'code': 'K2416', 'libelle': 'Linguiste'}, {'code': 'D1517', 'libelle': 'Chef / Cheffe de secteur distribution'}, {'code': 'M1228', 'libelle': 'Gestionnaire de risques financiers'}, {'code': 'D1440', 'libelle': 'Conseiller / Conseillère en livraison de véhicules'}, {'code': 'D1444', 'libelle': 'Responsable grands comptes'}, {'code': 'D1512', 'libelle': "Directeur régional / Directrice régionale d'hypermarché ou de supermarché"}, {'code': 'I1511', 'libelle': 'Technicien / Technicienne cordiste'}, {'code': 'I1512', 'libelle': 'Programmateur / Programmatrice des travaux sur cordes'}, {'code': 'C1125', 'libelle': 'Responsable gestion des sinistres'}, {'code': 'H2107', 'libelle': 'Opérateur / Opératrice de préparation de poissons et produits de la mer'}, {'code': 'N2103', 'libelle': 'Pilote instructeur / Pilote instructrice aéronautique'}, {'code': 'L1213', 'libelle': 'Auteur-compositeur-interprète / Auteure-compositrice-interprète'}, {'code': 'L1212', 'libelle': 'Chanteur / Chanteuse'}, {'code': 'K2324', 'libelle': 'Ferrailleur / Ferrailleuse de métal'}, {'code': 'F1712', 'libelle': 'Ferrailleur / Ferrailleuse du BTP'}, {'code': 'H2806', 'libelle': 'Technicien / Technicienne fusion en industrie verrière'}, {'code': 'D1254', 'libelle': 'Vendeur / Vendeuse en articles de papeterie et loisirs créatifs'}, {'code': 'L1316', 'libelle': "Conducteur / Conductrice d'antenne"}, {'code': 'L1318', 'libelle': 'Scripte de fiction'}, {'code': 'E1134', 'libelle': 'Scénariste'}, {'code': 'L1314', 'libelle': 'Chargé / Chargée de programme'}, {'code': 'L1313', 'libelle': 'Programmateur / Programmatrice salle de cinéma'}, {'code': 'H2106', 'libelle': 'Technicien / Technicienne de fabrication en industrie alimentaire'}, {'code': 'H3409', 'libelle': 'Polisseur / Polisseuse sur verre'}, {'code': 'H1410', 'libelle': 'Ingénieur / Ingénieure de gestion de la production'}, {'code': 'M1722', 'libelle': 'Chargé / Chargée de cession de droits, synchro'}, {'code': 'L1319', 'libelle': 'Directeur / Directrice artistique éditions de musique et phonographique'}, {'code': 'H2516', 'libelle': 'Technicien / Technicienne de production du travail des métaux'}, {'code': 'K1611', 'libelle': 'Iconographe'}, {'code': 'D1513', 'libelle': 'Chef / Cheffe de rayon produits frais'}, {'code': 'J1141', 'libelle': 'Orthodontiste'}, {'code': 'I1120', 'libelle': 'Responsable technique en camping'}, {'code': 'H1311', 'libelle': 'Responsable en santé environnementale'}, {'code': 'H1535', 'libelle': 'Technicien / Technicienne qualité produit et métrologie en mécanique et travail des métaux'}, {'code': 'L1320', 'libelle': 'Directeur / Directrice de label'}, {'code': 'M1434', 'libelle': "Développeur / Développeuse d'audience"}, {'code': 'M1721', 'libelle': 'Chef / Cheffe de projet édition phonographique'}, {'code': 'L1312', 'libelle': 'Administrateur / Administratrice de tournées'}, {'code': 'K1741', 'libelle': 'Maître de pont sur navire militaire'}, {'code': 'K2511', 'libelle': 'Agent / Agente de sûreté ferroviaire'}, {'code': 'B1816', 'libelle': "Tisserand / Tisserande d'art"}, {'code': 'E1316', 'libelle': 'Conducteur / Conductrice de machines à sérigraphier'}, {'code': 'H2511', 'libelle': "Responsable d'atelier de blanchisserie industrielle"}, {'code': 'N2104', 'libelle': 'Instructeur / Instructrice Personnel Navigant Commercial (PNC)'}, {'code': 'L1214', 'libelle': "Chef / Cheffe d'orchestre"}, {'code': 'N4306', 'libelle': "Agent / Agente d'accompagnement des trains"}, {'code': 'N3111', 'libelle': 'Officier électronicien / Officière électronicienne'}, {'code': 'D1249', 'libelle': 'Vendeur / Vendeuse de cuisines'}, {'code': 'D1439', 'libelle': 'Représentant / Représentante en biens et en services auprès des entreprises'}, {'code': 'E1214', 'libelle': 'Superviseur / Superviseuse de production virtuelle'}, {'code': 'L1315', 'libelle': 'Documentariste'}, {'code': 'F1713', 'libelle': 'Maçon-fumiste / Maçonne-fumiste'}, {'code': 'A1220', 'libelle': 'Jardinier / Jardinière paysagiste en terrain de sport'}, {'code': 'N4135', 'libelle': 'Conducteur / Conductrice de véhicule de guidage'}, {'code': 'I1210', 'libelle': 'Agent de maintenance qualifié / Agente de maintenance qualifiée en camping'}, {'code': 'H2811', 'libelle': 'Plieur / Plieuse de verre plat'}, {'code': 'H3411', 'libelle': 'Laqueur industriel / Laqueuse industrielle'}, {'code': 'L1317', 'libelle': 'Directeur / Directrice de casting'}, {'code': 'L1310', 'libelle': 'Directeur / Directrice de salle de spectacles'}, {'code': 'N4134', 'libelle': 'Conducteur / Conductrice de véhicule de protection de convoi exceptionnel'}, {'code': 'K1739', 'libelle': 'Opérateur / Opératrice en navigation maritime sur navire militaire'}, {'code': 'H2108', 'libelle': 'Boulanger pâtissier industriel / Boulangère pâtissière industrielle'}, {'code': 'K2326', 'libelle': 'Agent / Agente de mise en fourrière animale'}, {'code': 'N4405', 'libelle': "Agent / Agente d'exploitation du réseau ferré"}, {'code': 'K2414', 'libelle': 'Paléontologue'}, {'code': 'N4133', 'libelle': 'Conducteur / Conductrice de véhicule grumier'}, {'code': 'H3410', 'libelle': 'Galvanoplaste industriel / Galvanoplaste industrielle'}, {'code': 'F1404', 'libelle': 'Technicien / Technicienne de forage pétrole et gaz'}, {'code': 'L1216', 'libelle': 'Acteur / Actrice de complément'}, {'code': 'H2712', 'libelle': "Technicien / Technicienne d'exploitation en centrale hydroélectrique"}, {'code': 'H3308', 'libelle': 'Emballeur industriel / Emballeuse industrielle'}, {'code': 'C1126', 'libelle': 'Contrôleur / Contrôleuse cotisations sociales'}, {'code': 'G1246', 'libelle': 'Animateur / Animatrice mobilité à vélo'}, {'code': 'H3204', 'libelle': 'Opérateur / Opératrice de production des matières plastiques et du caoutchouc'}, {'code': 'H2711', 'libelle': 'Opérateur / Opératrice consoliste en raffinerie'}, {'code': 'H2513', 'libelle': "Chef / Cheffe d'équipe et d'atelier cuir et peaux"}, {'code': 'D1250', 'libelle': 'Libraire'}, {'code': 'K1515', 'libelle': 'Inspecteur / Inspectrice du permis de conduire et de la sécurité routière'}, {'code': 'H2514', 'libelle': 'Ingénieur / Ingénieure en génie des matériaux'}, {'code': 'H1407', 'libelle': 'Responsable méthodes-industrialisation'}, {'code': 'H1313', 'libelle': 'Ingénieur / Ingénieure sécurité incendie'}, {'code': 'H2922', 'libelle': 'Fondeur / Fondeuse en métaux précieux'}, {'code': 'N4205', 'libelle': "Responsable d'exploitation transport routier de marchandises"}, {'code': 'N2211', 'libelle': 'Planificateur régulateur vol / Planificatrice régulatrice vol'}, {'code': 'M1720', 'libelle': 'Category Manager Responsable (CATMAN)'}, {'code': 'D1516', 'libelle': 'Responsable merchandising'}, {'code': 'K1748', 'libelle': 'Garde républicain / Garde républicaine'}, {'code': 'H1246', 'libelle': "Technicien / Technicienne en bureau d'études aéronautiques"}, {'code': 'K1610', 'libelle': "Régisseur d'œuvres d'art / Régisseuse d'œuvres d'art"}, {'code': 'H2809', 'libelle': 'Opérateur / Opératrice de poste centralisé en cimenterie'}, {'code': 'H2810', 'libelle': 'Agent / Agente technique de centrale à enrobés'}, {'code': 'D1120', 'libelle': 'Tourier / Tourière'}, {'code': 'D1514', 'libelle': 'Agent / Agente de péage'}, {'code': 'J1140', 'libelle': 'Cardiologue'}, {'code': 'G1248', 'libelle': "Agent / Agente d'accueil en cinéma"}, {'code': 'G1249', 'libelle': 'Responsable de hall de cinéma'}, {'code': 'C1211', 'libelle': 'Guichetier vendeur / Guichetière vendeuse'}, {'code': 'D1245', 'libelle': 'Vendeur / Vendeuse en parfumerie'}, {'code': 'H2512', 'libelle': "Responsable d'atelier de fabrication de produits non-tissés"}, {'code': 'B1104', 'libelle': 'Artiste peintre'}, {'code': 'K1614', 'libelle': 'Directeur / Directrice de médiathèque'}, {'code': 'N4406', 'libelle': 'Caténairiste'}, {'code': 'D1252', 'libelle': "Chef / Cheffe d'équipe de vente en pièces de rechange et d'accessoires de véhicules"}, {'code': 'H2924', 'libelle': 'Conducteur / Conductrice de ligne de production en industrie métallurgique'}, {'code': 'H3205', 'libelle': 'Technicien / Technicienne de production en matériaux composites'}, {'code': 'K1913', 'libelle': 'Médiateur / Médiatrice judiciaire'}, {'code': 'K1914', 'libelle': 'Responsable de service juridique'}, {'code': 'K1915', 'libelle': 'Avocat / Avocate'}, {'code': 'K1911', 'libelle': 'Fiscaliste'}, {'code': 'C1306', 'libelle': 'Gestionnaire financier / Gestionnaire financière'}, {'code': 'G1418', 'libelle': 'Directeur / Directrice de salle de cinéma'}, {'code': 'E1213', 'libelle': 'Responsable technique de la projection'}, {'code': 'E1212', 'libelle': 'Restaurateur / Restauratrice numérique image'}, {'code': 'H2716', 'libelle': 'Opérateur / Opératrice de centrale solaire'}, {'code': 'I1514', 'libelle': 'Technicien / Technicienne en dépollution'}, {'code': 'F1212', 'libelle': "Ingénieur / Ingénieure d'exploitation de gisements"}, {'code': 'H2515', 'libelle': "Chef / Cheffe d'atelier en industrie de transformation"}, {'code': 'K1746', 'libelle': 'Receveur placier / Receveuse placière'}, {'code': 'H1408', 'libelle': 'Programmeur / Programmeuse en Conception de Fabrication Assistée par Ordinateur (CFAO)'}, {'code': 'B1618', 'libelle': 'Vitrailliste'}, {'code': 'M1896', 'libelle': 'Analyste cycle de vie dans les télécoms'}, {'code': 'K1740', 'libelle': 'Expert / Experte en opérations spatiales militaires'}, {'code': 'N1210', 'libelle': 'Logisticien / Logisticienne'}, {'code': 'H2919', 'libelle': 'Charpentier / Charpentière métallique en construction navale'}, {'code': 'C1304', 'libelle': "Gestionnaire d'organisme de placement collectif en valeurs mobilières -OPCVM-"}, {'code': 'G1417', 'libelle': 'Exploitant / Exploitante de casino de jeux'}, {'code': 'G1244', 'libelle': 'Directeur / Directrice des jeux'}, {'code': 'C1129', 'libelle': 'Responsable grands comptes assurances'}, {'code': 'C1118', 'libelle': 'Responsable de secteur en assurances'}, {'code': 'C1116', 'libelle': "Chargé / Chargée de clientèle centre d'appels en assurances"}, {'code': 'C1213', 'libelle': "Directeur / Directrice d'organisme de crédit"}, {'code': 'H2921', 'libelle': 'Ouvrier / Ouvrière de montage en construction automobile'}, {'code': 'E1130', 'libelle': "Chargé / Chargée d'édition musicale graphique"}, {'code': 'K1743', 'libelle': 'Agent de surveillance de la voie publique (ASVP) / Agente de surveillance de la voie publique (ASVP)'}, {'code': 'K2513', 'libelle': 'Gardien / Gardienne de locaux'}, {'code': 'B1617', 'libelle': "Coutelier / Coutelière d'art"}, {'code': 'H2920', 'libelle': 'Prototypiste en mécanique'}, {'code': 'J1137', 'libelle': 'Néphrologue'}, {'code': 'H1245', 'libelle': 'Mécatronicien / Mécatronicienne'}, {'code': 'C1402', 'libelle': 'Agent / Agente technique des régimes de retraite complémentaire et de prévoyance'}, {'code': 'K1228', 'libelle': 'Ecrivain public / Ecrivaine publique'}, {'code': 'A1512', 'libelle': 'Dentiste équin'}, {'code': 'K1613', 'libelle': 'Archiviste'}, {'code': 'H3309', 'libelle': 'Préparateur / Préparatrice de mélange en industrie'}, {'code': 'C1115', 'libelle': 'Conseiller retraite / Conseillère retraite'}, {'code': 'K1110', 'libelle': 'Tuteur / Tutrice aux majeurs protégés'}, {'code': 'C1212', 'libelle': 'Conseiller / Conseillère à distance de banque'}, {'code': 'C1215', 'libelle': 'Contrôleur / Contrôleuse de banque'}, {'code': 'C1122', 'libelle': 'Contrôleur / Contrôleuse prestations de la sécurité sociale'}, {'code': 'C1214', 'libelle': "Chargé / Chargée d'études crédits bancaires"}, {'code': 'K1229', 'libelle': 'Médiateur administratif / Médiatrice administrative'}, {'code': 'K1916', 'libelle': 'Mandataire de justice'}, {'code': 'L1528', 'libelle': 'Machiniste de prise de vues'}, {'code': 'H3307', 'libelle': 'Agent / Agente de silo'}, {'code': 'F1146', 'libelle': 'Géomètre expert / Géomètre experte'}, {'code': 'M1895', 'libelle': 'Géomaticien / Géomaticienne'}, {'code': 'M1433', 'libelle': 'Géographe'}, {'code': 'D1248', 'libelle': 'Conseiller / Conseillère en matériel médical ou paramédical'}, {'code': 'H1109', 'libelle': "Chargé / Chargée d'affaires nucléaire"}, {'code': 'C1217', 'libelle': 'Conseiller commercial / Conseillère commerciale de banque'}, {'code': 'I1211', 'libelle': "Agent / Agente d'exploitation de stationnement"}, {'code': 'H3306', 'libelle': 'Responsable de silo'}, {'code': 'C1128', 'libelle': 'Rédacteur / Rédactrice règlement assurances'}, {'code': 'C1216', 'libelle': 'Rédacteur / Rédactrice Banque de France'}, {'code': 'F1211', 'libelle': "Responsable d'exploitation de gisements pétrole et gaz"}, {'code': 'K1114', 'libelle': 'Psychologue scolaire'}, {'code': 'K1113', 'libelle': 'Psychologue du travail'}, {'code': 'H1409', 'libelle': 'Ingénieur / Ingénieure soudage'}, {'code': 'H2807', 'libelle': 'Bobineur / Bobineuse de fils et fibres de verre'}, {'code': 'M1435', 'libelle': 'Chargé de tracking vérificateur / Chargée de tracking vérificatrice'}, {'code': 'D1443', 'libelle': "Chargé / Chargée d'assistance"}, {'code': 'H2220', 'libelle': 'Agent / Agente de montage en ameublement'}, {'code': 'H2219', 'libelle': "Agent / Agente d'encadrement en ameublement"}, {'code': 'H2218', 'libelle': 'Responsable de production en industrie du bois'}, {'code': 'H2217', 'libelle': 'Responsable de scierie'}, {'code': 'I1121', 'libelle': 'Ingénieur de maintenance / Ingénieure de maintenance'}, {'code': 'I1212', 'libelle': "Opérateur / Opératrice d'installation ou maintenance industrielle"}, {'code': 'K2606', 'libelle': "Directeur / Directrice d'entreprise funéraire"}, {'code': 'D1244', 'libelle': 'Tatoueur / Tatoueuse'}, {'code': 'D1246', 'libelle': 'Vendeur / Vendeuse en accessoires de la personne'}, {'code': 'K1912', 'libelle': 'Formaliste'}, {'code': 'C1507', 'libelle': 'Chargé / Chargée de recouvrement immobilier'}, {'code': 'C1120', 'libelle': 'Conseiller / Conseillère en études actuarielles'}, {'code': 'H2216', 'libelle': 'Responsable de parc à grumes'}, {'code': 'I1336', 'libelle': 'Technicien / Technicienne froid embarqué routier'}, {'code': 'C1305', 'libelle': 'Opérateur / Opératrice sur marchés financiers'}, {'code': 'H2808', 'libelle': 'Conducteur / Conductrice de presses en production transformation du verre'}, {'code': 'H3106', 'libelle': 'Conducteur / Conductrice de ligne en industrie papetière'}, {'code': 'K1816', 'libelle': 'Manager de commerce et territoire'}, {'code': 'M1432', 'libelle': 'Office manager'}, {'code': 'K1514', 'libelle': "Inspecteur / Inspectrice de l'action sanitaire et sociale"}, {'code': 'C1127', 'libelle': 'Expert / Experte à distance sinistres et dommages en assurances'}, {'code': 'C1403', 'libelle': 'Cadre technique de la banque'}, {'code': 'K1425', 'libelle': "Délégué / Déléguée de l'Assurance Maladie (DAM)"}, {'code': 'C1123', 'libelle': 'Chef / Cheffe de service de la sécurité sociale'}, {'code': 'H2109', 'libelle': "Pilote d'installation automatisée en industrie alimentaire"}, {'code': 'G1709', 'libelle': "Agent / Agente d'accueil et de prévention en camping"}, {'code': 'D1253', 'libelle': 'Disquaire'}, {'code': 'K1609', 'libelle': "Technicien / Technicienne en manipulation d'œuvres d'art"}, {'code': 'M1227', 'libelle': 'Gestionnaire de droits et de redevance'}, {'code': 'C1119', 'libelle': "Chargé / Chargée d'affaires en assurances"}, {'code': 'K2415', 'libelle': 'Paléographe'}, {'code': 'J1138', 'libelle': 'Sexologue'}, {'code': 'N2209', 'libelle': 'Superviseur / Superviseuse piste'}, {'code': 'G1247', 'libelle': "Surveillant / Surveillante d'espaces aquatiques"}, {'code': 'L1311', 'libelle': 'Chargé / Chargée de production de spectacles'}, {'code': 'C1508', 'libelle': 'Assistant / Assistante de gestion syndic immobilier'}, {'code': 'J1142', 'libelle': 'Angiologue'}, {'code': 'K1742', 'libelle': 'Contrôleur / Contrôleuse des espaces maritimes'}, {'code': 'L1215', 'libelle': 'Humoriste'}, {'code': 'F1403', 'libelle': 'Foreur / Foreuse pétrole et gaz'}, {'code': 'I1636', 'libelle': 'Mécanicien / Mécanicienne cabine'}, {'code': 'F1506', 'libelle': 'Ouvrier / Ouvrière de la construction modulaire hors-site'}, {'code': 'C1117', 'libelle': 'Courtier automobile / Courtière automobile'}, {'code': 'C1210', 'libelle': 'Vendeur / Vendeuse en devises'}, {'code': 'G1245', 'libelle': 'Accompagnateur / Accompagnatrice en moyenne montagne'}, {'code': 'D1247', 'libelle': 'Vendeur / Vendeuse en articles de puériculture'}, {'code': 'H2925', 'libelle': 'Armurier / Armurière de fabrication'}, {'code': 'H2923', 'libelle': "Ajusteur-régleur / Ajusteuse-régleuse de fabrication en instruments d'optique"}, {'code': 'I1635', 'libelle': 'Mécanicien / Mécanicienne structure avion'}, {'code': 'D1515', 'libelle': 'Agent / Agente de billetterie'}, {'code': 'J1416', 'libelle': 'Chiropracteur / Chiropractrice'}, {'code': 'K1112', 'libelle': 'Addictologue'}, {'code': 'D1251', 'libelle': 'Vendeur de tabac-presse / Vendeuse de tabac-presse'}, {'code': 'H1243', 'libelle': 'Technicien / Technicienne en bioproduction'}, {'code': 'H1242', 'libelle': 'Responsable de développement industriel en bioproduction'}, {'code': 'H1244', 'libelle': 'Formulateur / Formulatrice de produits alimentaires'}, {'code': 'H1310', 'libelle': 'Responsable sécurité sanitaire en agroalimentaire'}, {'code': 'C1130', 'libelle': 'Gestionnaire en protection sociale'}, {'code': 'M1226', 'libelle': 'Responsable investissements'}, {'code': 'M1833', 'libelle': 'Ingénieur / Ingénieure sécurité web'}, {'code': 'M1856', 'libelle': 'Expert / Experte en cybersécurité'}, {'code': 'B1102', 'libelle': "Mosaïste d'art"}, {'code': 'F1624', 'libelle': 'Staffeur Stuqueur / Staffeuse Stuqueuse'}, {'code': 'A1206', 'libelle': 'Concepteur / Conceptrice paysagiste'}, {'code': 'B1103', 'libelle': 'Sculpteur / Sculptrice'}, {'code': 'A1213', 'libelle': 'Conducteur / Conductrice de travaux forestiers'}, {'code': 'H2417', 'libelle': 'Conducteur / Conductrice de rame textile'}, {'code': 'A1425', 'libelle': 'Ramendeur / Ramendeuse'}, {'code': 'N1108', 'libelle': 'Conducteur / Conductrice de grue mobile'}, {'code': 'J1204', 'libelle': "Directeur / Directrice de laboratoire d'analyses de biologie médicale"}, {'code': 'M1611', 'libelle': 'Secrétaire Facturier / Facturière'}, {'code': 'M1825', 'libelle': 'Coordinateur / Coordinatrice de production web'}, {'code': 'G1227', 'libelle': 'Guide-interprète'}, {'code': 'I1506', 'libelle': 'Superviseur / Superviseuse cordiste'}, {'code': 'N4120', 'libelle': 'Chauffeur-livreur préparateur / Chauffeuse-livreuse préparatrice de commandes'}, {'code': 'M1613', 'libelle': 'Télésecrétaire'}, {'code': 'N1110', 'libelle': 'Magasinier / Magasinière'}, {'code': 'G1707', 'libelle': 'Responsable de vestia

In [108]:
# Pour avoir une observation de structure plus lisible

print(json.dumps(resultat_rome, indent=4, ensure_ascii=False))

[
    {
        "code": "N2215",
        "libelle": "Coordonnateur / Coordonnatrice zone avion"
    },
    {
        "code": "N4207",
        "libelle": "Régulateur / Régulatrice poste central transport sanitaire de personnes"
    },
    {
        "code": "L1321",
        "libelle": "Directeur / Directrice de production de spectacles"
    },
    {
        "code": "I1639",
        "libelle": "Contrôleur / Contrôleuse de moteurs d'avions"
    },
    {
        "code": "N2217",
        "libelle": "Chef d'équipe contrôleur aérien / Cheffe d'équipe contrôleuse aérienne"
    },
    {
        "code": "K1924",
        "libelle": "Clerc de commissaire de justice"
    },
    {
        "code": "K1923",
        "libelle": "Clerc de commissaire-priseur"
    },
    {
        "code": "K1231",
        "libelle": "Patient partenaire / Patiente partenaire en santé"
    },
    {
        "code": "K1429",
        "libelle": "Administrateur / Administratrice de l'Etat"
    },
    {
        "code": "K1428",
        "libelle": "Conseiller / Conseillère de cabinet ministériel"
    },
    {
        "code": "K2515",
        "libelle": "Agent / Agente cynotechnique en détection des explosifs"
    },
    {
        "code": "I1411",
        "libelle": "Agent / Agente de reconditionnement numérique"
    },
    {
        "code": "C1124",
        "libelle": "Technicien / Technicienne sécurité sociale"
    },
    {
        "code": "K1109",
        "libelle": "Graphothérapeute"
    },
    {
        "code": "K1111",
        "libelle": "Psychanalyste"
    },
    {
        "code": "J1136",
        "libelle": "Gérontologue"
    },
    {
        "code": "J1139",
        "libelle": "Neurochirurgien / Neurochirurgienne"
    },
    {
        "code": "K2325",
        "libelle": "Technicien / Technicienne d'exploitation méthanisation"
    },
    {
        "code": "K2416",
        "libelle": "Linguiste"
    },
    {
        "code": "D1517",
        "libelle": "Chef / Cheffe de secteur distribution"
    },
    {
        "code": "M1228",
        "libelle": "Gestionnaire de risques financiers"
    },
    {
        "code": "D1440",
        "libelle": "Conseiller / Conseillère en livraison de véhicules"
    },
    {
        "code": "D1444",
        "libelle": "Responsable grands comptes"
    },
    {
        "code": "D1512",
        "libelle": "Directeur régional / Directrice régionale d'hypermarché ou de supermarché"
    },
    {
        "code": "I1511",
        "libelle": "Technicien / Technicienne cordiste"
    },
    {
        "code": "I1512",
        "libelle": "Programmateur / Programmatrice des travaux sur cordes"
    },
    {
        "code": "C1125",
        "libelle": "Responsable gestion des sinistres"
    },
    {
        "code": "H2107",
        "libelle": "Opérateur / Opératrice de préparation de poissons et produits de la mer"
    },
    {
        "code": "N2103",
        "libelle": "Pilote instructeur / Pilote instructrice aéronautique"
    },
    {
        "code": "L1213",
        "libelle": "Auteur-compositeur-interprète / Auteure-compositrice-interprète"
    },
    {
        "code": "L1212",
        "libelle": "Chanteur / Chanteuse"
    },
    {
        "code": "K2324",
        "libelle": "Ferrailleur / Ferrailleuse de métal"
    },
    {
        "code": "F1712",
        "libelle": "Ferrailleur / Ferrailleuse du BTP"
    },
    {
        "code": "H2806",
        "libelle": "Technicien / Technicienne fusion en industrie verrière"
    },
    {
        "code": "D1254",
        "libelle": "Vendeur / Vendeuse en articles de papeterie et loisirs créatifs"
    },
    {
        "code": "L1316",
        "libelle": "Conducteur / Conductrice d'antenne"
    },
    {
        "code": "L1318",
        "libelle": "Scripte de fiction"
    },
    {
        "code": "E1134",
        "libelle": "Scénariste"
    },
    {
        "code": "L1314",
        "libelle": "Chargé / Chargée de programme"
    },
    {
        "code": "L1313",
        "libelle": "Programmateur / Programmatrice salle de cinéma"
    },
    {
        "code": "H2106",
        "libelle": "Technicien / Technicienne de fabrication en industrie alimentaire"
    },
    {
        "code": "H3409",
        "libelle": "Polisseur / Polisseuse sur verre"
    },
    {
        "code": "H1410",
        "libelle": "Ingénieur / Ingénieure de gestion de la production"
    },
    {
        "code": "M1722",
        "libelle": "Chargé / Chargée de cession de droits, synchro"
    },
    {
        "code": "L1319",
        "libelle": "Directeur / Directrice artistique éditions de musique et phonographique"
    },
    {
        "code": "H2516",
        "libelle": "Technicien / Technicienne de production du travail des métaux"
    },
    {
        "code": "K1611",
        "libelle": "Iconographe"
    },
    {
        "code": "D1513",
        "libelle": "Chef / Cheffe de rayon produits frais"
    },
    {
        "code": "J1141",
        "libelle": "Orthodontiste"
    },
    {
        "code": "I1120",
        "libelle": "Responsable technique en camping"
    },
    {
        "code": "H1311",
        "libelle": "Responsable en santé environnementale"
    },
    {
        "code": "H1535",
        "libelle": "Technicien / Technicienne qualité produit et métrologie en mécanique et travail des métaux"
    },
    {
        "code": "L1320",
        "libelle": "Directeur / Directrice de label"
    },
    {
        "code": "M1434",
        "libelle": "Développeur / Développeuse d'audience"
    },
    {
        "code": "M1721",
        "libelle": "Chef / Cheffe de projet édition phonographique"
    },
    {
        "code": "L1312",
        "libelle": "Administrateur / Administratrice de tournées"
    },
    {
        "code": "K1741",
        "libelle": "Maître de pont sur navire militaire"
    },
    {
        "code": "K2511",
        "libelle": "Agent / Agente de sûreté ferroviaire"
    },
    {
        "code": "B1816",
        "libelle": "Tisserand / Tisserande d'art"
    },
    {
        "code": "E1316",
        "libelle": "Conducteur / Conductrice de machines à sérigraphier"
    },
    {
        "code": "H2511",
        "libelle": "Responsable d'atelier de blanchisserie industrielle"
    },
    {
        "code": "N2104",
        "libelle": "Instructeur / Instructrice Personnel Navigant Commercial (PNC)"
    },
    {
        "code": "L1214",
        "libelle": "Chef / Cheffe d'orchestre"
    },
    {
        "code": "N4306",
        "libelle": "Agent / Agente d'accompagnement des trains"
    },
    {
        "code": "N3111",
        "libelle": "Officier électronicien / Officière électronicienne"
    },
    {
        "code": "D1249",
        "libelle": "Vendeur / Vendeuse de cuisines"
    },
    {
        "code": "D1439",
        "libelle": "Représentant / Représentante en biens et en services auprès des entreprises"
    },
    {
        "code": "E1214",
        "libelle": "Superviseur / Superviseuse de production virtuelle"
    },
    {
        "code": "L1315",
        "libelle": "Documentariste"
    },
    {
        "code": "F1713",
        "libelle": "Maçon-fumiste / Maçonne-fumiste"
    },
    {
        "code": "A1220",
        "libelle": "Jardinier / Jardinière paysagiste en terrain de sport"
    },
    {
        "code": "N4135",
        "libelle": "Conducteur / Conductrice de véhicule de guidage"
    },
    {
        "code": "I1210",
        "libelle": "Agent de maintenance qualifié / Agente de maintenance qualifiée en camping"
    },
    {
        "code": "H2811",
        "libelle": "Plieur / Plieuse de verre plat"
    },
    {
        "code": "H3411",
        "libelle": "Laqueur industriel / Laqueuse industrielle"
    },
    {
        "code": "L1317",
        "libelle": "Directeur / Directrice de casting"
    },
    {
        "code": "L1310",
        "libelle": "Directeur / Directrice de salle de spectacles"
    },
    {
        "code": "N4134",
        "libelle": "Conducteur / Conductrice de véhicule de protection de convoi exceptionnel"
    },
    {
        "code": "K1739",
        "libelle": "Opérateur / Opératrice en navigation maritime sur navire militaire"
    },
    {
        "code": "H2108",
        "libelle": "Boulanger pâtissier industriel / Boulangère pâtissière industrielle"
    },
    {
        "code": "K2326",
        "libelle": "Agent / Agente de mise en fourrière animale"
    },
    {
        "code": "N4405",
        "libelle": "Agent / Agente d'exploitation du réseau ferré"
    },
    {
        "code": "K2414",
        "libelle": "Paléontologue"
    },
    {
        "code": "N4133",
        "libelle": "Conducteur / Conductrice de véhicule grumier"
    },
    {
        "code": "H3410",
        "libelle": "Galvanoplaste industriel / Galvanoplaste industrielle"
    },
    {
        "code": "F1404",
        "libelle": "Technicien / Technicienne de forage pétrole et gaz"
    },
    {
        "code": "L1216",
        "libelle": "Acteur / Actrice de complément"
    },
    {
        "code": "H2712",
        "libelle": "Technicien / Technicienne d'exploitation en centrale hydroélectrique"
    },
    {
        "code": "H3308",
        "libelle": "Emballeur industriel / Emballeuse industrielle"
    },
    {
        "code": "C1126",
        "libelle": "Contrôleur / Contrôleuse cotisations sociales"
    },
    {
        "code": "G1246",
        "libelle": "Animateur / Animatrice mobilité à vélo"
    },
    {
        "code": "H3204",
        "libelle": "Opérateur / Opératrice de production des matières plastiques et du caoutchouc"
    },
    {
        "code": "H2711",
        "libelle": "Opérateur / Opératrice consoliste en raffinerie"
    },
    {
        "code": "H2513",
        "libelle": "Chef / Cheffe d'équipe et d'atelier cuir et peaux"
    },
    {
        "code": "D1250",
        "libelle": "Libraire"
    },
    {
        "code": "K1515",
        "libelle": "Inspecteur / Inspectrice du permis de conduire et de la sécurité routière"
    },
    {
        "code": "H2514",
        "libelle": "Ingénieur / Ingénieure en génie des matériaux"
    },
    {
        "code": "H1407",
        "libelle": "Responsable méthodes-industrialisation"
    },
    {
        "code": "H1313",
        "libelle": "Ingénieur / Ingénieure sécurité incendie"
    },
    {
        "code": "H2922",
        "libelle": "Fondeur / Fondeuse en métaux précieux"
    },
    {
        "code": "N4205",
        "libelle": "Responsable d'exploitation transport routier de marchandises"
    },
    {
        "code": "N2211",
        "libelle": "Planificateur régulateur vol / Planificatrice régulatrice vol"
    },
    {
        "code": "M1720",
        "libelle": "Category Manager Responsable (CATMAN)"
    },
    {
        "code": "D1516",
        "libelle": "Responsable merchandising"
    },
    {
        "code": "K1748",
        "libelle": "Garde républicain / Garde républicaine"
    },
    {
        "code": "H1246",
        "libelle": "Technicien / Technicienne en bureau d'études aéronautiques"
    },
    {
        "code": "K1610",
        "libelle": "Régisseur d'œuvres d'art / Régisseuse d'œuvres d'art"
    },
    {
        "code": "H2809",
        "libelle": "Opérateur / Opératrice de poste centralisé en cimenterie"
    },
    {
        "code": "H2810",
        "libelle": "Agent / Agente technique de centrale à enrobés"
    },
    {
        "code": "D1120",
        "libelle": "Tourier / Tourière"
    },
    {
        "code": "D1514",
        "libelle": "Agent / Agente de péage"
    },
    {
        "code": "J1140",
        "libelle": "Cardiologue"
    },
    {
        "code": "G1248",
        "libelle": "Agent / Agente d'accueil en cinéma"
    },
    {
        "code": "G1249",
        "libelle": "Responsable de hall de cinéma"
    },
    {
        "code": "C1211",
        "libelle": "Guichetier vendeur / Guichetière vendeuse"
    },
    {
        "code": "D1245",
        "libelle": "Vendeur / Vendeuse en parfumerie"
    },
    {
        "code": "H2512",
        "libelle": "Responsable d'atelier de fabrication de produits non-tissés"
    },
    {
        "code": "B1104",
        "libelle": "Artiste peintre"
    },
    {
        "code": "K1614",
        "libelle": "Directeur / Directrice de médiathèque"
    },
    {
        "code": "N4406",
        "libelle": "Caténairiste"
    },
    {
        "code": "D1252",
        "libelle": "Chef / Cheffe d'équipe de vente en pièces de rechange et d'accessoires de véhicules"
    },
    {
        "code": "H2924",
        "libelle": "Conducteur / Conductrice de ligne de production en industrie métallurgique"
    },
    {
        "code": "H3205",
        "libelle": "Technicien / Technicienne de production en matériaux composites"
    },
    {
        "code": "K1913",
        "libelle": "Médiateur / Médiatrice judiciaire"
    },
    {
        "code": "K1914",
        "libelle": "Responsable de service juridique"
    },
    {
        "code": "K1915",
        "libelle": "Avocat / Avocate"
    },
    {
        "code": "K1911",
        "libelle": "Fiscaliste"
    },
    {
        "code": "C1306",
        "libelle": "Gestionnaire financier / Gestionnaire financière"
    },
    {
        "code": "G1418",
        "libelle": "Directeur / Directrice de salle de cinéma"
    },
    {
        "code": "E1213",
        "libelle": "Responsable technique de la projection"
    },
    {
        "code": "E1212",
        "libelle": "Restaurateur / Restauratrice numérique image"
    },
    {
        "code": "H2716",
        "libelle": "Opérateur / Opératrice de centrale solaire"
    },
    {
        "code": "I1514",
        "libelle": "Technicien / Technicienne en dépollution"
    },
    {
        "code": "F1212",
        "libelle": "Ingénieur / Ingénieure d'exploitation de gisements"
    },
    {
        "code": "H2515",
        "libelle": "Chef / Cheffe d'atelier en industrie de transformation"
    },
    {
        "code": "K1746",
        "libelle": "Receveur placier / Receveuse placière"
    },
    {
        "code": "H1408",
        "libelle": "Programmeur / Programmeuse en Conception de Fabrication Assistée par Ordinateur (CFAO)"
    },
    {
        "code": "B1618",
        "libelle": "Vitrailliste"
    },
    {
        "code": "M1896",
        "libelle": "Analyste cycle de vie dans les télécoms"
    },
    {
        "code": "K1740",
        "libelle": "Expert / Experte en opérations spatiales militaires"
    },
    {
        "code": "N1210",
        "libelle": "Logisticien / Logisticienne"
    },
    {
        "code": "H2919",
        "libelle": "Charpentier / Charpentière métallique en construction navale"
    },
    {
        "code": "C1304",
        "libelle": "Gestionnaire d'organisme de placement collectif en valeurs mobilières -OPCVM-"
    },
    {
        "code": "G1417",
        "libelle": "Exploitant / Exploitante de casino de jeux"
    },
    {
        "code": "G1244",
        "libelle": "Directeur / Directrice des jeux"
    },
    {
        "code": "C1129",
        "libelle": "Responsable grands comptes assurances"
    },
    {
        "code": "C1118",
        "libelle": "Responsable de secteur en assurances"
    },
    {
        "code": "C1116",
        "libelle": "Chargé / Chargée de clientèle centre d'appels en assurances"
    },
    {
        "code": "C1213",
        "libelle": "Directeur / Directrice d'organisme de crédit"
    },
    {
        "code": "H2921",
        "libelle": "Ouvrier / Ouvrière de montage en construction automobile"
    },
    {
        "code": "E1130",
        "libelle": "Chargé / Chargée d'édition musicale graphique"
    },
    {
        "code": "K1743",
        "libelle": "Agent de surveillance de la voie publique (ASVP) / Agente de surveillance de la voie publique (ASVP)"
    },
    {
        "code": "K2513",
        "libelle": "Gardien / Gardienne de locaux"
    },
    {
        "code": "B1617",
        "libelle": "Coutelier / Coutelière d'art"
    },
    {
        "code": "H2920",
        "libelle": "Prototypiste en mécanique"
    },
    {
        "code": "J1137",
        "libelle": "Néphrologue"
    },
    {
        "code": "H1245",
        "libelle": "Mécatronicien / Mécatronicienne"
    },
    {
        "code": "C1402",
        "libelle": "Agent / Agente technique des régimes de retraite complémentaire et de prévoyance"
    },
    {
        "code": "K1228",
        "libelle": "Ecrivain public / Ecrivaine publique"
    },
    {
        "code": "A1512",
        "libelle": "Dentiste équin"
    },
    {
        "code": "K1613",
        "libelle": "Archiviste"
    },
    {
        "code": "H3309",
        "libelle": "Préparateur / Préparatrice de mélange en industrie"
    },
    {
        "code": "C1115",
        "libelle": "Conseiller retraite / Conseillère retraite"
    },
    {
        "code": "K1110",
        "libelle": "Tuteur / Tutrice aux majeurs protégés"
    },
    {
        "code": "C1212",
        "libelle": "Conseiller / Conseillère à distance de banque"
    },
    {
        "code": "C1215",
        "libelle": "Contrôleur / Contrôleuse de banque"
    },
    {
        "code": "C1122",
        "libelle": "Contrôleur / Contrôleuse prestations de la sécurité sociale"
    },
    {
        "code": "C1214",
        "libelle": "Chargé / Chargée d'études crédits bancaires"
    },
    {
        "code": "K1229",
        "libelle": "Médiateur administratif / Médiatrice administrative"
    },
    {
        "code": "K1916",
        "libelle": "Mandataire de justice"
    },
    {
        "code": "L1528",
        "libelle": "Machiniste de prise de vues"
    },
    {
        "code": "H3307",
        "libelle": "Agent / Agente de silo"
    },
    {
        "code": "F1146",
        "libelle": "Géomètre expert / Géomètre experte"
    },
    {
        "code": "M1895",
        "libelle": "Géomaticien / Géomaticienne"
    },
    {
        "code": "M1433",
        "libelle": "Géographe"
    },
    {
        "code": "D1248",
        "libelle": "Conseiller / Conseillère en matériel médical ou paramédical"
    },
    {
        "code": "H1109",
        "libelle": "Chargé / Chargée d'affaires nucléaire"
    },
    {
        "code": "C1217",
        "libelle": "Conseiller commercial / Conseillère commerciale de banque"
    },
    {
        "code": "I1211",
        "libelle": "Agent / Agente d'exploitation de stationnement"
    },
    {
        "code": "H3306",
        "libelle": "Responsable de silo"
    },
    {
        "code": "C1128",
        "libelle": "Rédacteur / Rédactrice règlement assurances"
    },
    {
        "code": "C1216",
        "libelle": "Rédacteur / Rédactrice Banque de France"
    },
    {
        "code": "F1211",
        "libelle": "Responsable d'exploitation de gisements pétrole et gaz"
    },
    {
        "code": "K1114",
        "libelle": "Psychologue scolaire"
    },
    {
        "code": "K1113",
        "libelle": "Psychologue du travail"
    },
    {
        "code": "H1409",
        "libelle": "Ingénieur / Ingénieure soudage"
    },
    {
        "code": "H2807",
        "libelle": "Bobineur / Bobineuse de fils et fibres de verre"
    },
    {
        "code": "M1435",
        "libelle": "Chargé de tracking vérificateur / Chargée de tracking vérificatrice"
    },
    {
        "code": "D1443",
        "libelle": "Chargé / Chargée d'assistance"
    },
    {
        "code": "H2220",
        "libelle": "Agent / Agente de montage en ameublement"
    },
    {
        "code": "H2219",
        "libelle": "Agent / Agente d'encadrement en ameublement"
    },
    {
        "code": "H2218",
        "libelle": "Responsable de production en industrie du bois"
    },
    {
        "code": "H2217",
        "libelle": "Responsable de scierie"
    },
    {
        "code": "I1121",
        "libelle": "Ingénieur de maintenance / Ingénieure de maintenance"
    },
    {
        "code": "I1212",
        "libelle": "Opérateur / Opératrice d'installation ou maintenance industrielle"
    },
    {
        "code": "K2606",
        "libelle": "Directeur / Directrice d'entreprise funéraire"
    },
    {

In [109]:
# Afficher le premier métier retourné par l'API
if len(resultat_rome) > 0:
    print(resultat_rome[0])

{'code': 'N2215', 'libelle': 'Coordonnateur / Coordonnatrice zone avion'}

In [110]:
# Identifier les champs disponibles
if len(resultat_rome) > 0:
    print(resultat_rome[0].keys())

dict_keys(['code', 'libelle'])

## le reférentiel ROME

Notre première collecte : enrégistrer le reférentiel ROME

In [111]:
# Nous allons récupérer les données ROME et les transformer en Dataframe puis contrôler leurs qualité avant de les inclure dans le projet

# Transformons la liste des métiers resultat_rome en Dataframe
df_metiers_rome = pd.DataFrame(resultat_rome)

# Vérifions la structure
display(df_metiers_rome.head())

# Nous allons vérifier les dimensions
print(f"le nombre de lignes :", len(df_metiers_rome))

print(df_metiers_rome.info()) # Nous avons 2 colonnes et 1923 lignes 

print(df_metiers_rome.columns.tolist())

    code                                            libelle
0  N2215          Coordonnateur / Coordonnatrice zone avion
1  N4207  Régulateur / Régulatrice poste central transpo...
2  L1321  Directeur / Directrice de production de specta...
3  I1639       Contrôleur / Contrôleuse de moteurs d'avions
4  N2217  Chef d'équipe contrôleur aérien / Cheffe d'équ...

le nombre de lignes : 1923
<class 'pandas.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   code     1923 non-null   str
 1   libelle  1923 non-null   str
dtypes: str(2)
memory usage: 30.2 KB
None
['code', 'libelle']

In [112]:
# Nous allons contrôler la qualité de nos données et si les codes sont repétés
print("Valeurs manquantes :")
print(df_metiers_rome.isna().sum())

print("Nombres de doublons :")
print(df_metiers_rome.duplicated().sum())

print("\nCode métier doublon : ")
print(df_metiers_rome["code"].duplicated().sum())

print("\nCode manquant : ")
print(df_metiers_rome["code"].isna().sum())

print("\nLibelle manquant : ")
print(df_metiers_rome["libelle"].isna().sum())

Valeurs manquantes :
code       0
libelle    0
dtype: int64
Nombres de doublons :
0

Code métier doublon :
0

Code manquant :
0

Libelle manquant :
0

In [113]:
df_metiers_rome.head()

    code                                            libelle
0  N2215          Coordonnateur / Coordonnatrice zone avion
1  N4207  Régulateur / Régulatrice poste central transpo...
2  L1321  Directeur / Directrice de production de specta...
3  I1639       Contrôleur / Contrôleuse de moteurs d'avions
4  N2217  Chef d'équipe contrôleur aérien / Cheffe d'équ...

In [114]:
# Nos données sont satisfaisantes, nous allons les charger
# Conserver la réponse originale de l'API

with open("data/raw/rome_metiers.json",
            "w",
            encoding = "utf-8",
            ) as fichier:
                json.dump(resultat_rome, fichier, ensure_ascii=False,indent=2)

In [115]:
# Enregistrer le dataframe

df_metiers_rome.to_csv(
                    "data/processed/rome_metiers.csv",
                    index=False,
                    encoding = "utf-8-sig"
            )

## API marché du travail
### Collecte des offres d'emploi

Nous avons défini le périmètre de notre collecte des offres d'emploi:

Territoire : France métropolitaine

Période : du premier trimestre 2023 au dernier trimestre disponible en 2026

Métiers : ensemble des métiers disponibles dans le référentiel ROME.

Secteurs : nomenclature d’activité disponible dans l’API, notamment NAF21.

Statistiques : offres d’emploi, en distinguant les offres France Travail et toutes les offres lorsque les données le permettent.

Avant de lancer une collecte à grande échelle, nous devons vérifier le nombre d'appels nécessaires et les paramètres géographiques, pour éviter une collecte trop volumineuse ou des données qui dépasseraient notre périmètre.

In [116]:
# Préparer la collecte offres d'emploi

# Nous allons repartir depuis notre df_offres qui étéit un test d'appel de l'api pour la région  75 aquitaine et codeActivite : A1203
# Nous allons vérifier les informations déjà présentes dans df_offres afin de définir notre périmètre pour notre collecte.

print("Dimensions : ", df_offres.shape)

print("Lister les colonnes : ", df_offres.columns.tolist())

print("Territoires : ", df_offres["codeTypeTerritoire"].unique())

print("Types Activités : ", df_offres["codeTypeActivite"].unique())

print("Types Nomenclatures : ", df_offres["codeNomenclature"].unique())

print("Périodes : ", df_offres["codePeriode"].min(), "à" , df_offres["codePeriode"].max() )

Dimensions :  (88, 13)
Lister les colonnes :  ['codeTypeTerritoire', 'codeTerritoire', 'libTerritoire', 'codeTypeActivite', 'codeActivite', 'libActivite', 'codeNomenclature', 'libNomenclature', 'codeTypePeriode', 'codePeriode', 'libPeriode', 'valeurPrincipaleNombre', 'valeurSecondairePourcentage']
Territoires :  <StringArray>
['REG']
Length: 1, dtype: str
Types Activités :  <StringArray>
['ROME']
Length: 1, dtype: str
Types Nomenclatures :  <StringArray>
['PE', 'PE-CUMUL12MOIS', 'TOFF', 'TOFF-CUMUL12MOIS']
Length: 4, dtype: str
Périodes :  2021T1 à 2026T2

In [117]:
# Vérifions so nous pouvons limiter la période de 2023T1 à 2026T2 pour notre collecte
# Filtrer la période d'étude

df_offres_periodes = df_offres[df_offres["codePeriode"].between("2023T1" , "2026T2 ")].copy()

print("Dimensions à filtrage : ", df_offres_periodes.shape)

print("Périodes conservées : ", sorted(df_offres_periodes["codePeriode"].unique()))

print("Nombre de lignes par nomenclature : ", df_offres_periodes["codeNomenclature"].value_counts())

Dimensions à filtrage :  (56, 13)
Périodes conservées :  ['2023T1', '2023T2', '2023T3', '2023T4', '2024T1', '2024T2', '2024T3', '2024T4', '2025T1', '2025T2', '2025T3', '2025T4', '2026T1', '2026T2']
Nombre de lignes par nomenclature :  codeNomenclature
PE                  14
PE-CUMUL12MOIS      14
TOFF                14
TOFF-CUMUL12MOIS    14
Name: count, dtype: int64

Nous remarquons que le filtrage conserve 14 trimestres, de 2023T1 à 2026T2, soit 56 lignes : 14 lignes pour chacune des quatre nomenclatures.

Nous allons définir le térritoire car notre périmètre est la France métropolitaine. 
Le code NAT désigne un niveau national, mais nous ne devons pas supposer qu'il exclut les territoires ultramarins sans vérifier la documentation.

France Travail distingue bien France métropolitaine et France entière dans son service Data Emploi. Nous devons donc identifier le code exact accepté par notre API avant de collecter les données.

Ainsi nous allons vérifier la structure des paramètres de notre API pour une autre région afin de vérifier l'équivalence et la cohérence avant la collecte.

In [118]:
# Nous allons vérifier le code géographique
# Nous allons vérifier les régions diponibles

In [119]:

import requests

url = (
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres"
)

# Nous allons tester pour la région 11 l'ile de france
payload = {
    "codeTypeTerritoire": "REG",
    "codeTerritoire": "11",
    "codeTypeActivite": "ROME",
    "codeActivite": "A1203",
    "codeTypePeriode": "TRIMESTRE",
    "codeTypeNomenclature": "ORIGINEOFF",
    "codeNomenclature": "TOFF"
}

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

response_11 = requests.post(
    url,
    json=payload,
    headers=headers
)

print("Statut :", response_11.status_code)
print("Type de contenu :", response_11.headers.get("Content-Type"))
print("Réponse :", response_11.text[:3000])

Statut : 200
Type de contenu : application/json
Réponse : {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)","listeValeursParPeriode":[{"datMaj":"2026-09-23T09:06:22.000+02:00","codeTypeTerritoire":"REG","codeTerritoire":"11","libTerritoire":"ILE-DE-FRANCE","codeTypeActivite":"ROME","codeActivite":"A1203","libActivite":"Agent / Agente d'entretien des espaces verts","codeNomenclature":"PE","libNomenclature":"Offres France Travail","codeTypePeriode":"TRIMESTRE","codePeriode":"2026T2","libPeriode":"2ème trimestre 2026","valeurPrincipaleNombre":180,"valeurSecondairePourcentage":0.0,"listeValeurParCaract":[{"codeTypeCaract":"TYPECTR","codeCaract":"CDI","libCaract":"CDI","nombre":80,"pourcentage":47.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD1","libCaract":"CDD < 1 mois","nombre":0,"pourcentage":2.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD2","libCaract":"CDD de 1 à 6 mois","nombre":40,"pourcentage":20.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD3","libCaract":"CDD > 6 mois","nombre":30,"pourcentage":18.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"AUTR","libCaract":"Autres (intérim, emplois aidés, apprentissage)","nombre":20,"pourcentage":13.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB1","libCaract":"0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB2","libCaract":"10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB3","libCaract":"50 à 250 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TAILLEETAB","codeCaract":"ETB4","libCaract":"250+ salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDI-ETB1","libCaract":"CDI - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD1-ETB1","libCaract":"CDD < 1 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD2-ETB1","libCaract":"CDD de 1 à 6 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD3-ETB1","libCaract":"CDD > 6 mois - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"AUTR-ETB1","libCaract":"Autres (intérim, emplois aidés, apprentissage) - 0 à 9 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDI-ETB2","libCaract":"CDI - 10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract":"TYPECTRxTAILLEETAB","codeCaract":"CDD1-ETB2","libCaract":"CDD < 1 mois - 10 à 49 salariés","nombre":0,"pourcentage":0.0,"masque":false},{"codeTypeCaract"

In [120]:
resultat_11 = response_11.json()

# Extraire les statistiques par périodes
valeurs_11 = resultat_11.get("listeValeursParPeriode", [])

df_offres_11 = pd.json_normalize(valeurs_11)

display(df_offres_11.head())

# Nous allons vérifier le libéllé du territoire

print("libTerritoire : ", df_offres_11["libTerritoire"][0])

,datMaj,codeTypeTerritoire,codeTerritoire,libTerritoire,codeTypeActivite,codeActivite,libActivite,codeNomenclature,libNomenclature,codeTypePeriode,codePeriode,libPeriode,valeurPrincipaleNombre,valeurSecondairePourcentage,listeValeurParCaract
0,2026-09-23T09:06:22.000+02:00,REG,11,ILE-DE-FRANCE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE,Offres France Travail,TRIMESTRE,2026T2,2ème trimestre 2026,180,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
1,2026-09-23T09:06:23.000+02:00,REG,11,ILE-DE-FRANCE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE-CUMUL12MOIS,Cumul 12 derniers mois offres France Travail,TRIMESTRE,2026T2,2ème trimestre 2026,660,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
2,2026-09-23T09:06:23.000+02:00,REG,11,ILE-DE-FRANCE,ROME,A1203,Agent / Agente d'entretien des espaces verts,TOFF,Toutes offres,TRIMESTRE,2026T2,2ème trimestre 2026,260,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
3,2026-09-23T09:06:23.000+02:00,REG,11,ILE-DE-FRANCE,ROME,A1203,Agent / Agente d'entretien des espaces verts,TOFF-CUMUL12MOIS,Cumul 12 derniers mois toutes offres,TRIMESTRE,2026T2,2ème trimestre 2026,920,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."
4,2026-09-23T09:06:22.000+02:00,REG,11,ILE-DE-FRANCE,ROME,A1203,Agent / Agente d'entretien des espaces verts,PE,Offres France Travail,TRIMESTRE,2026T1,1er trimestre 2026,220,0.0,"[{'codeTypeCaract': 'TYPECTR', 'codeCaract': '..."

libTerritoire :  ILE-DE-FRANCE

In [121]:
# Affichons la nomenclature de df_offres
print(df_offres_11.columns)
print(df_offres_11['codeNomenclature'].value_counts())

Index(['datMaj', 'codeTypeTerritoire', 'codeTerritoire', 'libTerritoire',
       'codeTypeActivite', 'codeActivite', 'libActivite', 'codeNomenclature',
       'libNomenclature', 'codeTypePeriode', 'codePeriode', 'libPeriode',
       'valeurPrincipaleNombre', 'valeurSecondairePourcentage',
       'listeValeurParCaract'],
      dtype='str')
codeNomenclature
PE                  22
PE-CUMUL12MOIS      22
TOFF                22
TOFF-CUMUL12MOIS    22
Name: count, dtype: int64

In [122]:
# Varifieer le territoire

df_offres_11[["codeTerritoire","libTerritoire"]].drop_duplicates()

  codeTerritoire  libTerritoire
0             11  ILE-DE-FRANCE

In [123]:
# Le nombre de métier ROME enregistrer
print(df_metiers_rome.columns)
print("Nombres de code métier : ", len(df_metiers_rome))
display(df_metiers_rome.head())

Index(['code', 'libelle'], dtype='str')
Nombres de code métier :  1923

    code                                            libelle
0  N2215          Coordonnateur / Coordonnatrice zone avion
1  N4207  Régulateur / Régulatrice poste central transpo...
2  L1321  Directeur / Directrice de production de specta...
3  I1639       Contrôleur / Contrôleuse de moteurs d'avions
4  N2217  Chef d'équipe contrôleur aérien / Cheffe d'équ...

In [124]:
# La liste des codes d'activité
df_metiers_rome["code"].tolist()

['N2215',
 'N4207',
 'L1321',
 'I1639',
 'N2217',
 'K1924',
 'K1923',
 'K1231',
 'K1429',
 'K1428',
 'K2515',
 'I1411',
 'C1124',
 'K1109',
 'K1111',
 'J1136',
 'J1139',
 'K2325',
 'K2416',
 'D1517',
 'M1228',
 'D1440',
 'D1444',
 'D1512',
 'I1511',
 'I1512',
 'C1125',
 'H2107',
 'N2103',
 'L1213',
 'L1212',
 'K2324',
 'F1712',
 'H2806',
 'D1254',
 'L1316',
 'L1318',
 'E1134',
 'L1314',
 'L1313',
 'H2106',
 'H3409',
 'H1410',
 'M1722',
 'L1319',
 'H2516',
 'K1611',
 'D1513',
 'J1141',
 'I1120',
 'H1311',
 'H1535',
 'L1320',
 'M1434',
 'M1721',
 'L1312',
 'K1741',
 'K2511',
 'B1816',
 'E1316',
 'H2511',
 'N2104',
 'L1214',
 'N4306',
 'N3111',
 'D1249',
 'D1439',
 'E1214',
 'L1315',
 'F1713',
 'A1220',
 'N4135',
 'I1210',
 'H2811',
 'H3411',
 'L1317',
 'L1310',
 'N4134',
 'K1739',
 'H2108',
 'K2326',
 'N4405',
 'K2414',
 'N4133',
 'H3410',
 'F1404',
 'L1216',
 'H2712',
 'H3308',
 'C1126',
 'G1246',
 'H3204',
 'H2711',
 'H2513',
 'D1250',
 'K1515',
 'H2514',
 'H1407',
 'H1313',
 'H2922',
 'N4205',
 'N2211',
 'M1720',
 'D1516',
 'K1748',
 'H1246',
 'K1610',
 'H2809',
 'H2810',
 'D1120',
 'D1514',
 'J1140',
 'G1248',
 'G1249',
 'C1211',
 'D1245',
 'H2512',
 'B1104',
 'K1614',
 'N4406',
 'D1252',
 'H2924',
 'H3205',
 'K1913',
 'K1914',
 'K1915',
 'K1911',
 'C1306',
 'G1418',
 'E1213',
 'E1212',
 'H2716',
 'I1514',
 'F1212',
 'H2515',
 'K1746',
 'H1408',
 'B1618',
 'M1896',
 'K1740',
 'N1210',
 'H2919',
 'C1304',
 'G1417',
 'G1244',
 'C1129',
 'C1118',
 'C1116',
 'C1213',
 'H2921',
 'E1130',
 'K1743',
 'K2513',
 'B1617',
 'H2920',
 'J1137',
 'H1245',
 'C1402',
 'K1228',
 'A1512',
 'K1613',
 'H3309',
 'C1115',
 'K1110',
 'C1212',
 'C1215',
 'C1122',
 'C1214',
 'K1229',
 'K1916',
 'L1528',
 'H3307',
 'F1146',
 'M1895',
 'M1433',
 'D1248',
 'H1109',
 'C1217',
 'I1211',
 'H3306',
 'C1128',
 'C1216',
 'F1211',
 'K1114',
 'K1113',
 'H1409',
 'H2807',
 'M1435',
 'D1443',
 'H2220',
 'H2219',
 'H2218',
 'H2217',
 'I1121',
 'I1212',
 'K2606',
 'D1244',
 'D1246',
 'K1912',
 'C1507',
 'C1120',
 'H2216',
 'I1336',
 'C1305',
 'H2808',
 'H3106',
 'K1816',
 'M1432',
 'K1514',
 'C1127',
 'C1403',
 'K1425',
 'C1123',
 'H2109',
 'G1709',
 'D1253',
 'K1609',
 'M1227',
 'C1119',
 'K2415',
 'J1138',
 'N2209',
 'G1247',
 'L1311',
 'C1508',
 'J1142',
 'K1742',
 'L1215',
 'F1403',
 'I1636',
 'F1506',
 'C1117',
 'C1210',
 'G1245',
 'D1247',
 'H2925',
 'H2923',
 'I1635',
 'D1515',
 'J1416',
 'K1112',
 'D1251',
 'H1243',
 'H1242',
 'H1244',
 'H1310',
 'C1130',
 'M1226',
 'M1833',
 'M1856',
 'B1102',
 'F1624',
 'A1206',
 'B1103',
 'A1213',
 'H2417',
 'A1425',
 'N1108',
 'J1204',
 'M1611',
 'M1825',
 'G1227',
 'I1506',
 'N4120',
 'M1613',
 'N1110',
 'G1707',
 'M1836',
 'G1409',
 'H2425',
 'K1711',
 'N4122',
 'N4125',
 'G1708',
 'N4131',
 'M1616',
 'N1115',
 'K1719',
 'N1116',
 'K1210',
 'K1905',
 'M1612',
 'K2307',
 'G1806',
 'M1208',
 'M1209',
 'A1429',
 'K1712',
 'K1713',
 'K1714',
 'M1828',
 'K1715',
 'M1826',
 'M1839',
 'K1908',
 'K2408',
 'K2409',
 'K2410',
 'L1513',
 'G1611',
 'M1857',
 'E1112',
 'N4123',
 'M1615',
 'G1231',
 'H2210',
 'N2206',
 'C1506',
 'A1211',
 'I1318',
 'D1416',
 'D1218',
 'K2115',
 'K2117',
 'M1715',
 'D1417',
 'M1841',
 'M1858',
 'N4130',
 'N1111',
 'N1114',
 'K1724',
 'I1620',
 'K1718',
 'E1113',
 'N1305',
 'N3204',
 'B1403',
 'K2309',
 'G1234',
 'K1410',
 'M1854',
 'D1418',
 'M1614',
 'I1105',
 'M1410',
 'M1413',
 'D1219',
 'F1117',
 'K1722',
 'H1308',
 'F1126',
 'H1309',
 'M1823',
 'D1420',
 'K2506',
 'K1607',
 'H3305',
 'I1106',
 'D1109',
 'F1625',
 'M1210',
 'M1844',
 'F1125',
 'F1116',
 'I1504',
 'I1505',
 'H2702',
 'I1507',
 'K1720',
 'M1859',
 'G1107',
 'H1108',
 'N4132',
 'I1317',
 'I1319',
 'H2917',
 'M1861',
 'K1721',
 'B1614',
 'N4129',
 'F1207',
 'H2211',
 'G1232',
 'H1107',
 'A1507',
 'M1845',
 'M1846',
 'K1208',
 'K1209',
 'K2118',
 'I1405',
 'M1617',
 'J1413',
 'J1511',
 'M1412',
 'J1512',
 'M1855',
 'G1410',
 'G1229',
 'K1708',
 'H1513',
 'D1414',
 'H1406',
 'H1105',
 'N4109',
 'N4119',
 'N4127',
 'I1404',
 'K1717',
 'M1829',
 'M1847',
 'M1860',
 'F1115',
 'F1118',
 'F1119',
 'F1124',
 'F1123',
 'N4112',
 'G1223',
 'M1713',
 'K1710',
 'H1520',
 'K2205',
 'D1108',
 'N1107',
 'I1608',
 'D1302',
 'D1220',
 'G1807',
 'G1808',
 'G1705',
 'G1810',
 'G1805',
 'N4128',
 'H1307',
 'L1208',
 'G1412',
 'G1413',
 'I1320',
 'I1609',
 'G1230',
 'H1522',
 'F1121',
 'L1511',
 'G1226',
 'K1907',
 'L1206',
 'M1506',
 'H2424',
 'H3304',
 'H2915',
 'H2916',
 'I1314',
 'I1315',
 'N4117',
 'N2207',
 'M1414',
 'J1111',
 'G1108',
 'M1862',
 'M1863',
 'H2421',
 'J1108',
 'M1507',
 'H2423',
 'D1415',
 'F1504',
 'N4121',
 'K1716',
 'K2509',
 'I1208',
 'A1441',
 'A1432',
 'A1436',
 'J1133',
 'B1616',
 'K2137',
 'A1311',
 'A1446',
 'I1629',
 'N4305',
 'K2127',
 'L1518',
 'K1419',
 'I1509',
 'I1513',
 'N3110',
 'I1510',
 'K2419',
 'D1239',
 'N3207',
 'N1209',
 'N3210',
 'N3206',
 'H2715',
 'H2714',
 'K2420',
 'K2413',
 'K2417',
 'K2412',
 'K2418',
 'K2421',
 'H1312',
 'K1747',
 'I1632',
 'J1312',
 'N3205',
 'H1241',
 'B1702',
 'M1221',
 'F1133',
 'H1529',
 'I1631',
 'I1630',
 'D1119',
 'N3107',
 'M1431',
 'N2210',
 'A1510',
 'I1207',
 'M1509',
 'E1411',
 'M1212',
 'D1422',
 'N3211',
 'N3112',
 'G1504',
 'N1307',
 'N1308',
 'N1306',
 'J1118',
 'M1214',
 'J1134',
 'A1447',
 'H1532',
 'M1893',
 'N2208',
 'K1424',
 'K1423',
 'E1131',
 'E1133',
 'E1132',
 'K1817',
 'D1235',
 'E1122',
 'K1230',
 'N4404',
 'N3106',
 'N3115',
 'N3105',
 'H2713',
 'A1324',
 'N3208',
 'N3108',
 'N3117',
 'N3116',
 'N3109',
 'N3118',
 'I1633',
 'I1634',
 'I1637',
 'B1815',
 'N3113',
 'N3114',
 'J1127',
 'K1909',
 'K1510',
 'E1314',
 'I1335',
 'I1330',
 'E1413',
 'K2512',
 'K2514',
 'K1745',
 'K1744',
 'I1123',
 'I1122',
 'E1414',
 'E1409',
 'H2710',
 'F1626',
 'F1630',
 'N4303',
 'A1218',
 'A1221',
 'A1325',
 'A1321',
 'A1318',
 'K2319',
 'D1236',
 'B1404',
 'A1310',
 'M1876',
 'I1334',
 'A1445',
 'A1322',
 'A1317',
 'A1315',
 'A1316',
 'A1217',
 'D1438',
 'H1531',
 'L1516',
 'D1228',
 'D1511',
 'F1505',
 'H2509',
 'A1216',
 'A1219',
 'A1319',
 'M1306',
 'A1320',
 'H2510',
 'D1227',
 'D1233',
 'J1135',
 'A1444',
 'L1211',
 'A1215',
 'K1612',
 'K1608',
 'A1323',
 'G1243',
 'H1533',
 'I1322',
 'I1409',
 'K2604',
 'K2605',
 'A1314',
 'F1145',
 'F1144',
 'C1114',
 'C1121',
 'F1131',
 'A1442',
 'M1873',
 'J1415',
 'J1414',
 'J1112',
 'K1314',
 'D1114',
 'L1517',
 'K2321',
 'H2918',
 'H3105',
 'H3103',
 'H3104',
 'C1209',
 'K1227',
 'F1209',
 'M1225',
 'E1126',
 'K1727',
 'M1719',
 'E1315',
 'I1116',
 'J1117',
 'J1120',
 'F1132',
 'G1415',
 'G1416',
 'K2133',
 'K2134',
 'K2140',
 'K2135',
 'K2143',
 'K2125',
 'E1309',
 'H1525',
 'H2304',
 'K2322',
 'A1437',
 'A1433',
 'A1440',
 'K2120',
 'M1426',
 'M1884',
 'M1867',
 'M1878',
 'M1874',
 'K2507',
 'K2508',
 'D1436',
 'J1310',
 'J1311',
 'D1428',
 'D1432',
 'E1123',
 'E1312',
 'E1121',
 'E1120',
 'E1116',
 'E1114',
 'G1240',
 'H2105',
 'B1810',
 'B1813',
 'N3104',
 'E1311',
 'E1313',
 'I1406',
 'M1869',
 'M1871',
 'M1875',
 'M1881',
 'M1870',
 'K1220',
 'K1226',
 'K2130',
 'K2129',
 'K2122',
 'K1213',
 'E1118',
 'D1433',
 'K1414',
 'M1880',
 'K1221',
 'K1225',
 'K1810',
 'A1434',
 'G1242',
 'N1208',
 'H2215',
 'K2311',
 'H2212',
 'K2318',
 'E1128',
 'L1308',
 'L1306',
 'L1514',
 'L1522',
 'L1523',
 'K1219',
 'G1237',
 'K1413',
 'K1421',
 'K1415',
 'K1422',
 'M1890',
 'F1128',
 'F1129',
 'F1143',
 'F1138',
 'H1534',
 'H1527',
 'D1304',
 'J1121',
 'H2213',
 'F1208',
 'F1210',
 'K2147',
 'F1134',
 'L1527',
 'L1526',
 'L1525',
 'L1515',
 'I1324',
 'H1526',
 'I1321',
 'M1216',
 'G1241',
 'K1218',
 'K1216',
 'K1222',
 'K2144',
 'H1524',
 'K2320',
 'M1303',
 'K1725',
 'K2316',
 'F1142',
 'M1430',
 'H1226',
 'K2136',
 'F1711',
 'I1323',
 'K2314',
 'N4304',
 'F1629',
 'I1326',
 'I1332',
 'I1333',
 'F1628',
 'F1627',
 'I1209',
 'K2146',
 'K1217',
 'M1217',
 'K2128',
 'K2138',
 'K1417',
 'E1117',
 'L1104',
 'E1406',
 'E1404',
 'K1223',
 'M1417',
 'H2709',
 'K2317',
 'H1530',
 'D1423',
 'L1309',
 'L1307',
 'I1206',
 'I1109',
 'I1111',
 'I1118',
 'I1115',
 'I1410',
 'K2124',
 'K2141',
 'I1112',
 'I1108',
 'I1110',
 'I1117',
 'E1208',
 'E1209',
 'E1125',
 'L1524',
 'F1139',
 'F1140',
 'K2323',
 'D1303',
 'J1115',
 'I1508',
 'H1238',
 'G1306',
 'I1325',
 'J1130',
 'B1503',
 'D1305',
 'D1238',
 'D1234',
 'G1304',
 'G1307',
 'G1308',
 'M1718',
 'I1113',
 'I1119',
 'I1114',
 'K1734',
 'H2708',
 'H2707',
 'K2312',
 'K2315',
 'K1506',
 'K1511',
 'K1512',
 'K1509',
 'B1502',
 'B1504',
 'B1505',
 'G1235',
 'J1125',
 'J1128',
 'J1132',
 'E1403',
 'M1717',
 'M1886',
 'H1233',
 'E1115',
 'K2119',
 'H1230',
 'I1327',
 'K1738',
 'D1224',
 'D1421',
 'D1430',
 'K1508',
 'K1513',
 'L1519',
 'I1329',
 'I1408',
 'I1407',
 'H1234',
 'B1811',
 'B1809',
 'I1331',
 'F1303',
 'A1443',
 'K1108',
 'K2148',
 'M1508',
 'M1510',
 'M1511',
 'M1218',
 'M1427',
 'M1416',
 'D1427',
 'D1223',
 'D1434',
 'D1243',
 'D1110',
 'D1424',
 'I1623',
 'D1437',
 'H1227',
 'H1239',
 'F1130',
 'H1235',
 'H1528',
 'F1141',
 'F1137',
 'G1613',
 'G1612',
 'D1118',
 'D1115',
 'D1117',
 'M1887',
 'E1405',
 'M1428',
 'M1304',
 'K1815',
 'K1812',
 'K1814',
 'K2139',
 'D1425',
 'D1426',
 'I1627',
 'I1628',
 'A1214',
 'I1626',
 'I1625',
 'K1735',
 'K1729',
 'H1236',
 'H1228',
 'M1892',
 'M1889',
 'D1111',
 'A1438',
 'M1866',
 'D1113',
 'M1421',
 'M1418',
 'M1425',
 'K2411',
 'K2126',
 'K1107',
 'K1224',
 'K1215',
 'H1523',
 'M1415',
 'I1621',
 'I1622',
 'I1624',
 'D1230',
 'K1731',
 'K1736',
 'M1879',
 'G1238',
 'M1305',
 'L1521',
 'E1415',
 'E1407',
 'D1435',
 'K2121',
 'L1210',
 'K1910',
 'K1214',
 'M1885',
 'E1408',
 'M1512',
 'M1429',
 'M1424',
 'M1420',
 'M1872',
 'K1412',
 'K1418',
 'F1135',
 'K1732',
 'K1733',
 'K1737',
 'H2706',
 'G1239',
 'M1883',
 'D1232',
 'D1240',
 'D1241',
 'B1807',
 'B1812',
 'L1520',
 'I1328',
 'K2313',
 'G1236',
 'D1112',
 'L1209',
 'L1403',
 'A1439',
 'M1224',
 'M1215',
 'M1211',
 'M1220',
 'M1219',
 'K1804',
 'K1803',
 'K2131',
 'E1119',
 'E1127',
 'E1129',
 'E1210',
 'M1864',
 'E1412',
 'E1211',
 'H1229',
 'B1814',
 'B1808',
 'G1305',
 'D1229',
 ...]

In [125]:
# Nous allons tester de collecter pour 2 codes Activités pour éviter une grosse collecte 
payload_test = payload.copy()
payload_test["codeActivite"] = "D1512"
print(payload_test)

{'codeTypeTerritoire': 'REG', 'codeTerritoire': '11', 'codeTypeActivite': 'ROME', 'codeActivite': 'D1512', 'codeTypePeriode': 'TRIMESTRE', 'codeTypeNomenclature': 'ORIGINEOFF', 'codeNomenclature': 'TOFF'}

In [126]:
print(payload_test["codeTerritoire"])

11

In [127]:
url = (
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres"
)

headers = {
    "Authorization": f"Bearer {TOKEN}",
    "Content-Type": "application/json",
    "Accept": "application/json"
}

response = requests.post(
    url,
    json=payload_test,
    headers=headers
)

print("Statut API :", response.status_code)
print("Type de contenu :", response.headers.get("Content-Type"))
print("Réponse :", response.text[:1000])

Statut API : 200
Type de contenu : application/json
Réponse : {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)","listeValeursParPeriode":[{"datMaj":"2026-09-23T09:06:22.000+02:00","codeTypeTerritoire":"REG","codeTerritoire":"11","libTerritoire":"ILE-DE-FRANCE","codeTypeActivite":"ROME","codeActivite":"D1512","libActivite":"Directeur régional / Directrice régionale d'hypermarché ou de supermarché","codeNomenclature":"PE-CUMUL12MOIS","libNomenclature":"Cumul 12 derniers mois offres France Travail","codeTypePeriode":"TRIMESTRE","codePeriode":"2026T2","libPeriode":"2ème trimestre 2026","valeurPrincipaleNombre":0,"valeurSecondairePourcentage":0.0,"listeValeurParCaract":[{"codeTypeCaract":"TYPECTR","codeCaract":"CDI","libCaract":"CDI","nombre":0,"pourcentage":100.0,"masque":false},{"codeTypeCaract":"TYPECTR","codeCaract":"CDD1","libCaract":"CDD < 1 mois","no

In [128]:
# Convertissons la réponse actuelle en Dataframe
df_offres_test = pd.json_normalize(response.json()["listeValeursParPeriode"])

#display(df_offres_test)

# Observons les différentes péiodes er le territoire collecté

display(df_offres_test[["libPeriode", "codeTerritoire"]].drop_duplicates())
# Pour préparer la collecte des régions métropolitaines, nous allons vérifier les codes utilisés par l'API.

             libPeriode codeTerritoire
0   2ème trimestre 2026             11
3    1er trimestre 2026             11
6   4ème trimestre 2025             11
9   3ème trimestre 2025             11
13  2ème trimestre 2025             11
17   1er trimestre 2025             11
20  4ème trimestre 2024             11
24  3ème trimestre 2024             11
27  2ème trimestre 2024             11
30   1er trimestre 2024             11
34  4ème trimestre 2023             11
38  3ème trimestre 2023             11
41  2ème trimestre 2023             11
44   1er trimestre 2023             11
48  4ème trimestre 2022             11
52  3ème trimestre 2022             11
56  2ème trimestre 2022             11
60   1er trimestre 2022             11
64  4ème trimestre 2021             11
68  3ème trimestre 2021             11
70  2ème trimestre 2021             11
72   1er trimestre 2021             11

codeActivite accepte un seul code et pas une liste de code.

## Estimons le volume de notre collecte
Si nous collectons les 1 923 métiers dans les 12 régions métropolitaines, avec 2 nomenclatures (PE et TOFF), cela représenterait potentiellement :
- 1 923 métiers × 12 régions = 23 076 combinaisons métier-région.
- Si chaque requête renvoie les deux nomenclatures, environ 23 076 appels.
- Si une requête est nécessaire par nomenclature, environ 46 152 appels.

In [129]:
# Le nombre de lignes contenus dans ROME
nb_metiers = len(df_metiers_rome)
# La france métropolitaine compte 13 régions
nb_regions = 13

print("Nombre de métiers : ", nb_metiers)
print("Nombre de régions : ", nb_regions)
print("Nombre estimé d'appels : ", nb_metiers * nb_regions)

Nombre de métiers :  1923
Nombre de régions :  13
Nombre estimé d'appels :  24999

24 999 est le nombre d'appels estimé pour la collecte selon notre périmètre défini. Tout en sachant que certains métiers peuvent ne pas avoir de données pour certaines régions.

### Nous allons vérifier que les 13 régions sont bien accessibles avec leurs codes dans l'API France Travail.

In [130]:
# Les codes officielles des régions sont disponibles sur l'INSEE dans le code officiel géographique 2026

regions_metropolitaines = {
    "84": "AUVERGNE-RHONE-ALPES",
    "27": "BOURGOGNE-FRANCHE-COMTE",
    "53": "BRETAGNE",
    "24": "CENTRE-VAL DE LOIRE",
    "94": "CORSE",
    "44": "GRAND EST",
    "32": "HAUTS-DE-FRANCE",
    "11": "ILE-DE-FRANCE",
    "28": "NORMANDIE",
    "75": "NOUVELLE-AQUITAINE",
    "76": "OCCITANIE",
    "52": "PAYS DE LA LOIRE",
    "93": "PROVENCE-ALPES-COTE D'AZUR"
}

print("régions métropolitaines :", regions_metropolitaines)
print("nombre de régions : ", len(regions_metropolitaines))

régions métropolitaines : {'84': 'AUVERGNE-RHONE-ALPES', '27': 'BOURGOGNE-FRANCHE-COMTE', '53': 'BRETAGNE', '24': 'CENTRE-VAL DE LOIRE', '94': 'CORSE', '44': 'GRAND EST', '32': 'HAUTS-DE-FRANCE', '11': 'ILE-DE-FRANCE', '28': 'NORMANDIE', '75': 'NOUVELLE-AQUITAINE', '76': 'OCCITANIE', '52': 'PAYS DE LA LOIRE', '93': "PROVENCE-ALPES-COTE D'AZUR"}
nombre de régions :  13

In [131]:
# Véifions que l’API France Travail reconnaît ces codes,
# sachant que nous avaons déjà les régions 75 (Nouvelle Aquitaine) et 11 (Ile-de-France)
for code, region in regions_metropolitaines.items():
    payload_test["codeTerritoire"] = code
    response = requests.post(
        "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
        headers=headers,
        json=payload_test
    )

    if response.status_code == 200:
        data = response.json()["listeValeursParPeriode"]
        libelles = {
            ligne["libTerritoire"]
            for ligne in data}
        
        print(code,region,"->",libelles)
        
    else:
        print(code, region, "-> ERREUR", response.status_code)

84 AUVERGNE-RHONE-ALPES -> {'AUVERGNE-RHONE-ALPES'}
27 BOURGOGNE-FRANCHE-COMTE -> {'BOURGOGNE-FRANCHE-COMTE'}
53 BRETAGNE -> {'BRETAGNE'}
24 CENTRE-VAL DE LOIRE -> {'CENTRE-VAL DE LOIRE'}

KeyError: 'listeValeursParPeriode'

In [ ]:
print("Statut :", response.status_code)
print("Réponse :", response.text[:2000])

Statut : 200
Réponse : {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)"}

In [ ]:
print("Payload utilisé :", payload_test)
print("Réponse complète :", response.json())

Payload utilisé : {'codeTypeTerritoire': 'REG', 'codeTerritoire': '94', 'codeTypeActivite': 'ROME', 'codeActivite': 'D1512', 'codeTypePeriode': 'TRIMESTRE', 'codeTypeNomenclature': 'ORIGINEOFF', 'codeNomenclature': 'TOFF'}
Réponse complète : {'datMaj': '2026-09-23T11:04:21.000+02:00', 'codeIndicateur': 'OFF_1', 'codeFamille': 'OFFRES', 'libIndicateur': "Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)"}

In [ ]:
payload_test["codeTerritoire"] = "94"
payload_test["codeActivite"] = "A1203"

response = requests.post(
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
    headers=headers,
    json=payload_test
)

print("Statut :", response.status_code)
print("Réponse :", response.json())

Statut : 200

 On vérifie pourquoi ça bloque avec la CORSE, on va faire un test avec le métier qui fonctionnait déjà 'A1203'.
 Nous allons pour cela relancer la vérification des 13 régions avec A1203.

In [ ]:
for code, region in regions_metropolitaines.items():
    payload_test["codeTerritoire"] = code
    payload_test["codeActivite"] = "A1203"

    response = requests.post(
        "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
        headers=headers,
        json=payload_test
    )

    resultat = response.json()

    if response.status_code != 200:
        print(code, region, "-> ERREUR HTTP", response.status_code)
    elif "listeValeursParPeriode" not in resultat:
        print(code, region, "-> AUCUNE DONNÉE RETOURNÉE")
    else:
        libelles = {
            ligne["libTerritoire"]
            for ligne in resultat["listeValeursParPeriode"]
        }
        print(code, region, "->", libelles)

84 AUVERGNE-RHONE-ALPES -> {'AUVERGNE-RHONE-ALPES'}
27 BOURGOGNE-FRANCHE-COMTE -> {'BOURGOGNE-FRANCHE-COMTE'}
53 BRETAGNE -> {'BRETAGNE'}
24 CENTRE-VAL DE LOIRE -> {'CENTRE-VAL DE LOIRE'}
94 CORSE -> {'CORSE'}
44 GRAND EST -> {'GRAND EST'}
32 HAUTS-DE-FRANCE -> {'HAUTS-DE-FRANCE'}
11 ILE-DE-FRANCE -> {'ILE-DE-FRANCE'}
28 NORMANDIE -> {'NORMANDIE'}
75 NOUVELLE-AQUITAINE -> {'NOUVELLE-AQUITAINE'}
76 OCCITANIE -> {'OCCITANIE'}
52 PAYS DE LA LOIRE -> {'PAYS DE LA LOIRE'}
93 PROVENCE-ALPES-COTE D'AZUR -> {"PROVENCE-ALPES-COTE D'AZUR"}

Nous voyons que le test confirme que les 13 régions métropolitaines sont correctement reconnues par l’API France Travail avec le métier A1203.

### Testons la collecte d'un échantillon de métiers vue le nombre d'appel à venir

Ce test utilise les 10 premiers métiers sur les 13 régions du référentiel. Nous pourrons choisir un échantillon plus pertinent ensuite.
Ainsi nous aurons 130 requêtes ce qui nous permettra d'observer la disponibilité des données sans tout lancer.

In [ ]:
# Sélectionnons les 10 premiers métiers
echantillon_metiers = df_metiers_rome.head(10)
# la collecte sera stockée dans une liste
resultats_test = []

for code_metier in echantillon_metiers["code"] :
    for code_region, nom_region in regions_metropolitaines.items():
        payload_test["codeTerritoire"] = code_region
        payload_test["codeActivite"] = code_metier

        response = requests.post(
            "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
            headers=headers,
            json=payload_test
        )

        resultat = response.json()

        resultats_test.append({
            "code_metier" : code_metier,
            "code_region" : code_region,
            "region" : nom_region,
            "statut_http" : response.status_code,
            "donnees_presentes" : (
                "listeValeursParPeriode" in resultat
                and len(resultat.get("listeValeursParPeriode", [])) > 0
            )

        })
# Convertissons le résultat en dataframe

df_test_collecte = pd.DataFrame(resultats_test)

# affichons l'entête et quelques informations 

display(df_test_collecte.head())

print("Nombre de requêtes : ", len(df_test_collecte))
print("Réponses HTTP 200 : ", ((df_test_collecte["statut_http"] == 200).sum()))
print("Réponses avec données : ", ((df_test_collecte["donnees_presentes"]).sum()))
print("Réponses sans données : ", ((~df_test_collecte["donnees_presentes"]).sum()))

,code_metier,code_region,region,statut_http,donnees_presentes
0,N2215,84,AUVERGNE-RHONE-ALPES,404,False
1,N2215,27,BOURGOGNE-FRANCHE-COMTE,404,False
2,N2215,53,BRETAGNE,404,False
3,N2215,24,CENTRE-VAL DE LOIRE,404,False
4,N2215,94,CORSE,404,False

Nombre de requêtes :  130
Réponses HTTP 200 :  0
Réponses avec données :  0
Réponses sans données :  130

In [ ]:
# vérifions de manière individuel la requête du code_metier N2215 pour la région code 84
payload_test["codeTerritoire"] = "84"
payload_test["codeActivite"] = "N2215"

response = requests.post(
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
    headers=headers,
    json=payload_test
)

print("Statut HTTP :", response.status_code)
print("URL appelée :", response.url)
print("Type de contenu :", response.headers.get("Content-Type"))
print("Réponse :", response.text[:1000])

Statut HTTP : 404
URL appelée : https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres
Type de contenu : application/json
Réponse : {"message":"[FiltreErreurSldng] Erreur  lors de l'appel de l'Api REST 'POST:http://da084.z8-prod-mop.k8s.pole-emploi.intra/da084-smartemploi-sldng/v1/indicateur/stat-offres'. Status code = 404, message = Not Found","codeHttp":404}

In [ ]:
# Vérifions avec e code activité qui fonctionne déjà
payload_test["codeTerritoire"] = "84"
payload_test["codeActivite"] = "A1203"

response = requests.post(
    "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
    headers=headers,
    json=payload_test
)

print("Statut HTTP :", response.status_code)
print("Réponse :", response.text[:500])

Statut HTTP : 200
Réponse : {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractéristiques, % par activités (Rome, Secteur, Savoir-être, Compétence)","listeValeursParPeriode":[{"datMaj":"2026-09-23T09:06:22.000+02:00","codeTypeTerritoire":"REG","codeTerritoire":"84","libTerritoire":"AUVERGNE-RHONE-ALPES","codeTypeActivite":"ROME","codeActivite":"A1203","libActivite":"Agent / Agente d'entretien des e

In [ ]:
df_metiers_rome.head()

    code                                            libelle
0  N2215          Coordonnateur / Coordonnatrice zone avion
1  N4207  Régulateur / Régulatrice poste central transpo...
2  L1321  Directeur / Directrice de production de specta...
3  I1639       Contrôleur / Contrôleuse de moteurs d'avions
4  N2217  Chef d'équipe contrôleur aérien / Cheffe d'équ...

In [ ]:
# Nous allons tester un petit groupe de métiers pour la région 84
codes_test = ["A1203", "N2215", "N4207", "I1639", "N2217"]

for code in codes_test:
    payload_test["codeTerritoire"] = "84"
    payload_test["codeActivite"] = code

    response = requests.post(
        "https://api.francetravail.io/partenaire/stats-offres-demandes-emploi/v1/indicateur/stat-offres",
        headers=headers,
        json=payload_test
    )

    print(
        code,
        "-> HTTP", response.status_code,
        "|", response.text[:180]
    )

A1203 -> HTTP 200 | {"datMaj":"2026-09-23T11:04:21.000+02:00","codeIndicateur":"OFF_1","codeFamille":"OFFRES","libIndicateur":"Nombre et % d'offres par origine (Pole-emploi / Toutes offres) x caractér
N2215 -> HTTP 404 | {"message":"[FiltreErreurSldng] Erreur  lors de l'appel de l'Api REST 'POST:http://da084.z8-prod-mop.k8s.pole-emploi.intra/da084-smartemploi-sldng/v1/indicateur/stat-offres'. Statu
N4207 -> HTTP 404 | {"message":"[FiltreErreurSldng] Erreur  lors de l'appel de l'Api REST 'POST:http://da084.z8-prod-mop.k8s.pole-emploi.intra/da084-smartemploi-sldng/v1/indicateur/stat-offres'. Statu
I1639 -> HTTP 404 | {"message":"[FiltreErreurSldng] Erreur  lors de l'appel de l'Api REST 'POST:http://da084.z8-prod-mop.k8s.pole-emploi.intra/da084-smartemploi-sldng/v1/indicateur/stat-offres'. Statu
N2217 -> HTTP 404 | {"message":"[FiltreErreurSldng] Erreur  lors de l'appel de l'Api REST 'POST:http://da084.z8-prod-mop.k8s.pole-emploi.intra/da084-smartemploi-sldng/v1/indicateur/stat-offres'. Statu

In [134]:
codes_test = ["A1203", "N2215", "N4207", "I1639", "N2217"]

for code in codes_test:
    payload = {
        "codeTypeTerritoire": "REG",
        "codeTerritoire": "84",
        "codeTypeActivite": "ROME",
        "codeActivite": code,
        "codeTypePeriode": "TRIMESTRE",
        "codeTypeNomenclature": "ORIGINEOFF",
        "codeNomenclature": "TOFF"
    }

    response = requests.post(
        url,
        headers=headers,
        json=payload
    )

    print(code, "-> HTTP", response.status_code)

A1203 -> HTTP 200
N2215 -> HTTP 404
N4207 -> HTTP 404
I1639 -> HTTP 404
N2217 -> HTTP 404